<?php require_once 'support_file.php';?>
<?=(check_permission(basename($_SERVER['SCRIPT_NAME']))>0)? '' : header('Location: dashboard.php');
$title='CTC Transfer Report';
$now=time();
$unique='id';
$unique_field='id';
$table="code_to_code_master";
$table_details="code_to_code_transfer";
$journal_item="journal_item";

$page='Accounts_Code_to_Code_Transfer.php';
$ji_date=date('Y-m-d');
$crud      =new crud($table);
$$unique = $_GET[$unique];
$targeturl="<meta http-equiv='refresh' content='0;$page'>";
$dateTime = new DateTime('now', new DateTimeZone('Asia/Dhaka'));
$todayss=$dateTime->format("d/m/Y  h:i A");

if(prevent_multi_submit()){ 	
	if(isset($_POST['returned'])){   
	$up_master="UPDATE ".$table." SET status='RETURNED',return_comments='".$_POST[return_comments]."' where ".$unique."=".$$unique."";
    $update_table_master=mysqli_query($conn, $up_master);
    $up_details="UPDATE ".$table_details." SET status='RETURNED' where ".$unique_details."=".$$unique."";
    $update_table_details=mysqli_query($conn, $up_details);
    unset($_POST);
    unset($$unique);
    echo "<script>self.opener.location = '$page'; self.blur(); </script>";
    echo "<script>window.close(); </script>";
}

    //for modify PS information ...........................
    if(isset($_POST['checked']))
    {        
	 $maild = find_a_field('essential_info', 'ESS_CORPORATE_EMAIL','PBI_ID=' . $_POST[checked_by]);		
	 if ($maild != '') {
            $to = $maild;
				$subject = "A CTC Transfer Created!!";
				$message .= '<table border="0" cellpadding="0" cellspacing="0" width="100%"> 
    <tr>
        <td  align="center">
            <table border="0" cellpadding="0" cellspacing="0" width="600" class="responsive-table">                
                <tr>
                    <td align="center" valign="top" style="padding: 40px 0px 40px 0px;"><img alt="Example" src="http://icpbd-erp.com/51816/cmu_mod/icon/title.png" width="100" style="display: block;" border="0" class="responsive-image">
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" style="padding: 0px 10px 20px 10px;">
					<p style="font-family: sans-serif; font-size: 24px; font-weight: bold; line-height: 28px; margin: 0;">A Code to code transfer has been created!!</p>
                    </td>
                </tr>
                <tr>
                    <td align="center" valign="top" style="padding: 0px 10px 10px 10px;">
                        <p style="font-family: sans-serif; font-size: 13px; font-weight: normal; line-height: 24px; margin: 0;">A Code to Code transfer has been created. Your approval is required. CTC No is: <b>'.$$unique.'</b>.</p>
                    </td>
                </tr> 
            </table>
        </td>
    </tr>
	<tr>
	<td>
	<table align="center" border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse;font-family: sans-serif; font-size: 11px; padding-top:-200px" width="80%" class="responsive-table">                
                <tr bgcolor="#00a9f7">
                    <th align="center" valign="top">#</th>
					<th align="center" valign="top">Prepared By</th>
                </tr>
                <tr>
                    <th align="center" valign="top">Prepared By</th>
					<td style="padding-left:5px">'.find_a_field('user_activity_management','fname','user_id='.$_SESSION[userid]).'</td>
                </tr>
                <tr>
                    <th align="center" valign="top">Time </th>
					<td style="padding-left:5px">'.$_POST[entry_at].'</td>
                </tr>
				<tr>
                    <th align="center" valign="top">Remarks </th>
					<td style="padding-left:5px">'.$_POST[remarks].'</td>
                </tr> 
            </table></td>
	</tr>
</table>';
$message .= '<p align="center" valign="top" style="padding: 0px 10px 100px 10px;font-style:italic; font-size:10px">This EMAIL is automatically generated by ERP Software.</i>';
$from = 'erp@icpbd.com';
$headers = "";
$headers .= "From: ERP Software<erp@".$_SERVER['SERVER_NAME']."> \r\n";
$headers .= "Reply-To:" . $from . "\r\n" ."X-Mailer: PHP/" . phpversion();
$headers .= 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";  
$headers .= 'Cc:' . "\r\n";      
mail($to,$subject,$message,$headers); 
        }
		
		$results="Select srd.*,i.*
	from ".$table_details." srd, item_info i  where
    srd.transfer_from_item=i.item_id and 
    srd.".$unique."='".$_GET[$unique]."'";
    $query=mysqli_query($conn, $results);
	while($row=mysqli_fetch_array($query)){			
		    $_POST['id']='';
		    $_POST['ji_date'] = $ji_date;
            $_POST['item_id'] = $row[transfer_from_item];
            $_POST['warehouse_id'] = $row[warehouse_from];
            $_POST['item_ex'] = $row[t_qty];
            $_POST['item_price'] = $row[cct_rate];
            $_POST['total_amt'] = $row[amount];
            $_POST['tr_from'] = 'CodetocodeTransfer';
            $_POST['tr_no'] = $_GET[$unique];
            $_POST['sr_no'] = $row[ctct_id];
            $_POST[ip]=$ip;
            $crud      =new crud($journal_item);
            $crud->insert();
			
			 }
	
	$results=mysqli_query($conn, "Select srd.*,i.*,
	(select concat(item_id,' : ',item_name) from item_info where item_id=srd.transfer_to_item) as transfer_to_item
	from ".$table_details." srd, item_info i  where
    srd.transfer_from_item=i.item_id and 
    srd.".$unique."='".$_GET[$unique]."' order by srd.id desc");
	while($row=mysqli_fetch_array($results)){
		unset($_POST[item_ex]);
		$_POST['id']='';
		 $_POST['ji_date'] = $ji_date;
            $_POST['item_id'] = $row[transfer_to_item];
            $_POST['warehouse_id'] = $row[warehouse_from];
            $_POST['item_in'] = $row[ctct_qty];
            $_POST['item_price'] = $row[cct_rate];
            $_POST['total_amt'] = $row[amount];
            $_POST['tr_from'] = 'CodetocodeReceived';
            $_POST['tr_no'] = $_GET[$unique];
            $_POST['sr_no'] = $row[ctct_id];
            $_POST[ip]=$ip;
            $crud      =new crud($journal_item);
            $crud->insert();
	}
		
		
		
		$up_master=mysqli_query($conn,"UPDATE ".$table." SET status='COMPLETE',verify_at='".$todayss."' where ".$unique."=".$$unique."");
        $up_details=mysqli_query($conn,"UPDATE ".$table_deatils." SET status='COMPLETE' where ".$unique."=".$$unique."");
        $type=1;
        unset($_POST);
        echo "<script>window.close(); </script>";
    }}

// data query..................................
if(isset($$unique))
{   $condition=$unique."=".$$unique;
    $data=db_fetch_object($table,$condition);
    while (list($key, $value)=each($data))
    { $$key=$value;}}



    $results="Select srd.*,i.*,
	(select concat(item_id,' : ',item_name) from item_info where item_id=srd.transfer_to_item) as transfer_to_item
	from ".$table_details." srd, item_info i  where
    srd.transfer_from_item=i.item_id and 
    srd.".$unique."='".$$unique."' order by srd.id desc";
    $query=mysqli_query($conn, $results);
?>


<?php require_once 'header_content.php'; ?>
    <script type="text/javascript">
        function DoNavPOPUP(lk)
        {myWindow = window.open("<?=$page?>?<?=$unique?>="+lk, "myWindow", "toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no,directories=0,toolbar=0,scrollbars=1,location=0,statusbar=1,menubar=0,resizable=1,width=850,height=500,left = 230,top = -1");}
    </script>
<?php if(isset($_GET[$unique])){ 
 require_once 'body_content_without_menu.php'; } else {  
 require_once 'body_content.php'; } ?>



<?php if(isset($_GET[$unique])){ ?>
    <!-- input section-->
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_content">
                <form  name="addem" id="addem" class="form-horizontal form-label-left" method="post">
                    <? require_once 'support_html.php';?>
                  <table align="center" class="table table-striped table-bordered" style="width:100%; font-size:11px">
                <thead>
                <tr style="background-color: bisque">
                    <th>SL</th>
                    <th>Transfer From Code</th>
                    <th style="width:5%; text-align:center">UOM</th>
                    <th style="text-align:center;  width:10%">Transfer Qty</th>
                    <th style="text-align:center">Transfer to Code</th>
                    <th style="text-align:center; width:10%">Transfer to Qty</th>
                    <th style="text-align:center; width:10%">Unit Price</th>
                    <th style="text-align:center; width:10%">Amount</th>
                </tr>
                </thead>
                <tbody>


                <?php  while($row=mysqli_fetch_array($query)){  ?>
                    <tr>
                        <td style="width:3%; vertical-align:middle"><?=$i=$i+1;?></td>
                        <td style="vertical-align:middle; width: 25%"><?=$row[finish_goods_code];?> : <?=$row[item_name];?></td>
                        <td style="vertical-align:middle; text-align:center"><?=$row[unit_name];?></td>
                        <td align="center" style=" text-align:center;vertical-align:middle;"><?=$row[t_qty];?></td>
                        <td align="center" style=" text-align:left;vertical-align:middle;"><?=$row[transfer_to_item];?></td>
                        <td align="center" style=" text-align:right;vertical-align:middle;"><?=$row[ctct_qty];?></td>
                        <td align="center" style=" text-align:right;vertical-align:middle;"><?=$row[cct_rate]; ?></td>
                        <td align="center" style=" text-align:right;vertical-align:middle;"><?=$row[amount]; ?></td>
                    </tr>
                    <?php  } ?>
                </tbody>                
            </table>

 <?php
                                        $GET_status=find_a_field(''.$table.'','status',''.$unique.'='.$_GET[$unique]);
                                        if($GET_status=='CHECKED'){  ?>
                                            <p>
                                            <input type="text" id="return_comments"  name="return_comments" class="form-control col-md-7 col-xs-12"  style="width:166px;font-size: 11px; height:32px" placeholder="return comments........" ><button type="submit" name="returned" id="Return" class="btn btn-danger" onclick='return window.confirm("Are you confirm to Return?");' style="font-size: 12px;margin-left:10px;">Return the CTC Transfer</button>
                                                <button style="float: right;font-size: 12px;" type="submit" name="checked" id="checked" class="btn btn-success" onclick='return window.confirm("Are you confirm?");'>Checked & Forward</button>
                                            </p>
                                        <? } else {echo '<h6 style="text-align: center;color: red;  font-weight: bold"><i>This CTC has been checked!!</i></h6>';}?>
                    
                </form>
            </div>
        </div>
    </div>

<?php } ?>

<?php if(!isset($_GET[$unique])){ ?>
    <form  name="addem" id="addem" class="form-horizontal form-label-left" method="post" >
        <table align="center" style="width: 50%;">
            <tr><td>
                    <input type="date" style="width:150px; font-size: 11px; height: 25px"  value="<?php if(isset($_POST[f_date])) echo $_POST[f_date]; else echo date('Y-m-01');?>" max="<?=date('Y-m-d');?>" required   name="f_date" >
                <td style="width:10px; text-align:center"> -</td>
                <td><input type="date" style="width:150px;font-size: 11px; height: 25px"  value="<?php if(isset($_POST[t_date])) { echo $_POST[t_date]; } else { echo date('Y-m-d'); }?>" max="<?=date('Y-m-d')?>" required   name="t_date"></td>
                <td style="padding:10px"><button type="submit" style="font-size: 11px; height: 30px" name="viewreport"  class="btn btn-primary">View CTC Transfer Available</button></td>
            </tr></table>
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_content">
                    <table style="width:100%; font-size: 11px" class="table table-striped table-bordered">
                        <thead>
                        <tr style="background-color: bisque">
                            <th style="text-align:center">#</th>
                            <th style="text-align:center">CTC No</th>
                            <th style="text-align:center">CTC Date</th>
                            <th style="text-align:center">Remarks</th>
                            <th style="text-align:center">Wareehouse Name</th>
                            <th style="text-align:center">Entry By</th>
                            <th style="text-align:center">Entry At</th>
                            <th style="text-align:center">Status</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?
                        $from_date=date('Y-m-d' , strtotime($_POST[f_date]));
                        $to_date=date('Y-m-d' , strtotime($_POST[t_date]));
                        if(isset($_POST[viewreport])){
                            $res='select r.*,w.*,(SELECT concat(p2.PBI_NAME," # ","(",de.DESG_SHORT_NAME,")") FROM 							 
							personnel_basic_info p2,
							department d,
							designation de 
							 where 
							 p2.ERP_ID=r.entry_by and
							 p2.PBI_DESIGNATION=de.DESG_ID and  							 
							 p2.PBI_DEPARTMENT=d.DEPT_ID) as entry_by
				  from '.$table.' r,
				  warehouse w
				  WHERE 
				  r.warehouse_id=w.warehouse_id and 
				  r.ctct_date between "'.$from_date.'" and "'.$to_date.'"  	  
				   order by r.'.$unique.' DESC';
						} else {
							$res='select r.*,w.*,(SELECT concat(p2.PBI_NAME," # ","(",de.DESG_SHORT_NAME,")") FROM 							 
							personnel_basic_info p2,
							department d,
							designation de 
							 where 
							 p2.ERP_ID=r.entry_by and
							 p2.PBI_DESIGNATION=de.DESG_ID and  							 
							 p2.PBI_DEPARTMENT=d.DEPT_ID) as entry_by
				  from '.$table.' r,
				  warehouse w
				  WHERE 
				  r.warehouse_id=w.warehouse_id and 
				  r.status in ("CHECKED") 	  
				   order by r.'.$unique.' DESC';}
                            $pquery=mysqli_query($conn, $res);
                            while($req=mysqli_fetch_object($pquery)){ ?>
                                <tr style="cursor: pointer">
                                    <td onclick="DoNavPOPUP('<?=$req->$unique;?>', 'TEST!?', 600, 700)"><?=$i=$i+1;?></td>
                                    <td onclick="DoNavPOPUP('<?=$req->$unique;?>', 'TEST!?', 600, 700)"><?=$req->$unique;?></td>
                                    <td onclick="DoNavPOPUP('<?=$req->$unique;?>', 'TEST!?', 600, 700)"><?=$req->ctct_date;?></td>
                                    <td onclick="DoNavPOPUP('<?=$req->$unique;?>', 'TEST!?', 600, 700)"><?=$req->remarks;?></td>
                                    <td onclick="DoNavPOPUP('<?=$req->$unique;?>', 'TEST!?', 600, 700)"><?=$req->warehouse_name;?></td>
                                    <td onclick="DoNavPOPUP('<?=$req->$unique;?>', 'TEST!?', 600, 700)"><?=$req->entry_by;?></td>
                                    <td onclick="DoNavPOPUP('<?=$req->$unique;?>', 'TEST!?', 600, 700)"><?=$req->entry_at;?></td>
                                    <td onclick="DoNavPOPUP('<?=$req->$unique;?>', 'TEST!?', 600, 700)"><?=$req->status;?></td>
                                </tr>
                            <?php } ?></tbody></table>

                </div></div></div></form>
<?php } ?>

<?=$html->footer_content();?>