 <?php
require_once 'support_file.php';
$title="Apply for Early Leave";

$now=time();
$unique='id';
$unique_field='type';
$table="hrm_leave_info";
$page="hrm_apply_for_leave_view.php";
$crud      =new crud($table);
$$unique = $_GET[$unique];
$targeturl="<meta http-equiv='refresh' content='0;$page'>";

if(prevent_multi_submit()) {
    if(isset($_POST['record'])){		        	
		$ed=$_POST[e_date];
		$_POST[s_date]=$_POST[s_date];
        $_POST[e_date]=date('Y-m-d' , strtotime($ed));			
		$_POST[total_days]=		"0.5";
		$_POST[PBI_ID]=$_SESSION[PBI_ID];
		$_POST[leave_status] = "Waiting";
        $_POST[entry_at] = date('Y-m-d H:i:s');
		$_POST[half_or_full]='Half';
        $crud->insert();
		
		
$PBI_DEPT_HEADemail=$_POST[PBI_DEPT_HEAD];
$PBI_DEPT_RES=$_POST[leave_responsibility_name];
$myid=$_SESSION['PBI_ID'];
$name=find_a_field('personnel_basic_info','PBI_NAME','PBI_ID='.$myid);
$emailId=find_a_field('essential_info','ESS_CORPORATE_EMAIL','PBI_ID='.$PBI_DEPT_HEADemail);
$email_CC=find_a_field('essential_info','ESS_CORPORATE_EMAIL','PBI_ID='.$PBI_DEPT_RES);	
	
	 
		//if($emailId!=''){
				$to = $emailId;
				$subject = "Leave Application";
				$txt1 = "<p>Dear Sir,</p>				
				<p>A Leave Application is pending for your Authorization. Please enter employee access module to authorise the requisition. </p>				
				<p>Leave Requested By- ".$name."</p>				
				<p><b><i>This EMAIL is automatically generated by ERP Software.</i></b></p>";				
				$txt=$txt1.$txt2.$tr;				
				$from = 'erp@icpbd.com';
				$headers = "";
				$headers .= "From: ERP Software<erp@".$_SERVER['SERVER_NAME']."> \r\n";
$headers .= "Reply-To:" . $from . "\r\n" ."X-Mailer: PHP/" . phpversion();
$headers .= 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Cc:' .$email_CC. "\n";
$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";        
mail($to,$subject,$txt,$headers);
        $type=1;
        unset($_POST);
        unset($$unique);
		
    }
    
    
//for modify..................................
if(isset($_POST['modify']))
{
    $_POST['edit_at']=time();
    $_POST['edit_by']=$_SESSION['userid'];
    $crud->update($unique);
    $type=1; 
    echo "<script>window.close(); </script>";
}

//for Delete..................................
if(isset($_POST['delete']))
{   $condition=$unique."=".$$unique;
    $crud->delete($condition);
    unset($$unique);
    $type=1;
    $msg='Successfully Deleted.';    
    echo "<script>window.close(); </script>";
}}

// data query..................................
if(isset($$unique))
{   $condition=$unique."=".$$unique;
    $data=db_fetch_object($table,$condition);
    while (list($key, $value)=each($data))
    { $$key=$value;}}
	
	
	$sql_leave_responsibility_name="SELECT  p.PBI_ID,concat(p.PBI_ID_UNIQUE,' : ',p.PBI_NAME,' : ',d.DEPT_SHORT_NAME) FROM 
							 
							personnel_basic_info p,
							department d,
							essential_info e
							 where 
							 p.PBI_JOB_STATUS in ('In Service') and 							 
							 p.PBI_DEPARTMENT=d.DEPT_ID	and
							 p.PBI_ID=e.PBI_ID and 
							 e.ESS_JOB_LOCATION=1 group by p.PBI_ID							 
							  order by p.PBI_NAME";
	$sql_PBI_DEPT_HEAD="SELECT  p.PBI_ID,concat(p.PBI_ID_UNIQUE,' : ',p.PBI_NAME,' : ',d.DEPT_SHORT_NAME) FROM 
							 
							personnel_basic_info p,
							department d,
							essential_info e
							 where 
							 p.PBI_JOB_STATUS in ('In Service') and 							 
							 p.PBI_DEPARTMENT=d.DEPT_ID	and
							 p.PBI_ID=e.PBI_ID and 
							 e.ESS_JOB_LOCATION=1 group by p.PBI_ID					 
							  order by p.PBI_NAME";						  
							  
$sql2="select a.id,a.id,a.s_date as date,a.reason,a.leave_status from ".$table." a where a.PBI_ID=".$_SESSION[PBI_ID]." and a.half_or_full='Half' order by a.".$unique." desc limit 7";							  
?>



<?php require_once 'header_content.php'; ?>
<script type="text/javascript">
        function DoNavPOPUP(lk)
        {myWindow = window.open("<?=$page?>?<?=$unique?>="+lk, "myWindow", "toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no,directories=0,toolbar=0,scrollbars=1,location=0,statusbar=1,menubar=0,resizable=1,width=600,height=600,left = 383,top = -1");}
    </script>
<?php require_once 'body_content.php'; ?>



                    <!-- input section-->
                    <div class="col-md-8 col-sm-12 col-xs-12">
                        <div class="x_panel">
                            <div class="x_title">
                                <h2><?=$title;?></h2>
                                <ul class="nav navbar-right panel_toolbox">
                                    <div class="input-group pull-right">
                                        <!--a target="_new" class="btn btn-sm btn-default"  href="user_permission2.php">
                                            <i class="fa fa-plus-circle"></i> <span class="language" style="color:#000">Uer Permission (SUB)</span>
                                        </a-->
                                    </div>
                                </ul>
                                <div class="clearfix"></div>
                            </div>
                            <div class="x_content">

                                <form  name="addem" id="addem" style="font-size:11px" class="form-horizontal form-label-left" method="post">
                                    <? require_once 'support_html.php';?>
                                    
                                    <table style="width:100%"  cellpadding="0" cellspacing="0">
                                    <tr>
                                    <th style="width:15%">Type of Leave</th>
                                    <th style="width:1%; text-align:center">:</th>
                                    <td style="width: 35%">
                                        <select class="select2_single form-control" style="width:90%" name="type" id="type">
                                        <option value="Half" selected="selected">Early Leave</option>								   
									     </select>
                                        <input type="hidden" id="<?=$unique?>" style="width:90%"     name="<?=$unique?>" value="<?=$$unique?>" class="form-control col-md-7 col-xs-12" ></td>
                                        
                                        
                                                                          
                                    <th style="width:15%">Reason</th>
                                    <th style="width:1%; text-align:center">:</th>
                                    <td style="width: 35%"><input type="text" id="reason" style="width:90%; font-size:11px"  required value="<?=$reason;?>"   name="reason"   class="form-control col-md-7 col-xs-12" ></td>
                                    </tr>
                                    
                                    <tr><td style="height:5px"></td></tr>
                                    <tr>
                                    <th>Date</th>
                                    <th style="text-align:center">:</th>
                                    <td>
	            <input type="date" id="s_date" style="font-size:11px; width:90%" max="<?=date('Y-m-d');?>" value="<?=$s_date;?>"  required="required" name="s_date"  class="form-control col-md-7 col-xs-12" ></td>
                                        
                                        
                                    <th>Departure Time</th> 
                                    <th style="text-align:center">:</th>                                 
                                    <td>
       <input type="text" id="departure_time" style="width:90%; font-size:11px"  required   name="departure_time" value="<?=$departure_time;?>" class="form-control col-md-7 col-xs-12" ></td>
                                    </tr>
                                    
                                   
                                    <tr><td style="height:5px"></td></tr>
                                    <tr>
                                    <th>R.P During Leave</th> 
                                    <th style="text-align:center">:</th> 
                                    <td>
                                    <select style="width: 210px;margin-top: 2px;" class="select2_single form-control" name="leave_responsibility_name" id="leave_responsibility_name">
                      <option></option>
                       <?=advance_foreign_relation($sql_leave_responsibility_name,$leave_responsibility_name);?>
                      </select></td>
                                        
                                    <th>Authorised Person</th>    
                                    <th style="text-align:center">:</th>                                       
                                    <td>
           <select style="width: 198px;margin-top: 2px;" class="select2_single form-control" name="PBI_DEPT_HEAD" id="PBI_DEPT_HEAD">
                      <option></option>
                      <?=advance_foreign_relation($sql_PBI_DEPT_HEAD,$PBI_DEPT_HEAD);?>
                     </select></td>
                                    </tr>
                                    </table>
                                    
                                  

                                        <br>
                                        <?php if($_GET[$unique]){  ?>                                            
                                            <div class="form-group" style="margin-left:40%">
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                            <button type="submit" name="modify" id="modify" class="btn btn-success">Modify</button>
                                            </div></div>
                                            <? if($_SESSION['userid']=="10019"){?>                                            
                                             <div class="form-group" style="margin-left:40%;">
                                             <div class="col-md-6 col-sm-6 col-xs-12">
                                             <input  name="delete" type="submit" class="btn btn-danger" id="delete" value="Delete"/>
                                             </div></div>                                             
                                             <? }?>                                         
                                            <?php } else {?>                                           
                                            <div class="form-group" style="margin-left:40%">
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                            <button type="submit" name="record" id="record" style="font-size:12px" onclick='return window.confirm("Are you confirm?");' class="btn btn-primary">Submit the Application</button>
                                            </div></div>                                                                                        
                                            <?php } ?> 


                                </form>
                                </div>
                                </div>
                                </div>


<?=recentdataview($sql2,'voucher_view_popup_ismail.php','hrm_late_attendance','282px','Recent Applications','hrm_requisition_early_leave_report.php','4');?>        
<?=$html->footer_content();?> 