<?php
require_once 'support_file.php';
$title="Sample / Gift Requisition";

$dfrom=date('Y-1-1');
$dto=date('Y-m-d');

$now=time();

$table="requisition_sample_gift_master";
$unique = 'oi_no';   // Primary Key of this Database table
$table_details = 'requisition_sample_gift_details';
$details_unique = 'id';
$page="hrm_requisition_sample_gift.php";
$crud      =new crud($table);
$taken=getSVALUE("".$table_details."", "SUM(qty)", " where oi_date between '$dfrom' and '$dto' and status not in ('MANUAL') and  issued_to='".$_SESSION[PBI_ID]."' and item_id=".$_GET[item_code_GET]."");
$unit=getSVALUE("item_info", "unit_name", " where item_id=".$_GET[item_code_GET]."");
$department=getSVALUE("personnel_basic_info", "PBI_DEPARTMENT", " where PBI_ID=".$_SESSION[PBI_ID]."");
$targeturl="<meta http-equiv='refresh' content='0;$page'>";
$item_all= find_all_field('item_info','','item_id="'.$_GET[item_code_GET].'"');


if(prevent_multi_submit()){
   
    if(isset($_POST['initiate']))
    {		
		
		
		$_POST['section_id'] = $_SESSION['sectionid'];
		$_POST['company_id'] = $_SESSION['companyid'];
		
		$_POST['entry_by'] = $_SESSION['userid'];
        $_POST['entry_at'] = date('Y-m-d H:s:i');
		$sd=$_POST[oi_date]; 
		$_POST[oi_date]=date('Y-m-d' , strtotime($sd));
		
		$bhd=$_POST[by_when_date]; 
		$_POST[by_when_date]=date('Y-m-d' , strtotime($bhd));			
		
	    $_POST['issue_type'] = 'Office Issue';	
	    $_POST['status'] = 'MANUAL';
		$_POST['requisition_from'] = $department;
	    $_POST['warehouse_id'] = '11';
		$_POST['issued_to'] = $_SESSION[PBI_ID];
		$_SESSION['initiate_hrm_sample_gift_requisition']=$_POST[$unique];		
        $crud->insert();
        $type=1;
        $msg='New Entry Successfully Inserted.';		

        unset($_POST);
        unset($$unique);
    }
	
	
	if(isset($_POST['add']))
    {			
		
		$_POST['entry_by'] = $_SESSION['userid'];
        $_POST['entry_at'] = date('Y-m-d H:s:i');
		$sd=$_POST[oi_date]; 
		$_POST[oi_date]=date('Y-m-d' , strtotime($sd));		
	    $_POST['issue_type'] = 'Office Issue';	
	    $_POST['status'] = 'MANUAL';
		$_POST['requisition_from'] = $_SESSION["department"];
	    $_POST['warehouse_id'] = '11';
		$_POST['recommend_qty'] = $_POST['qty'];
		$_POST['request_qty'] = $_POST['qty'];
		$_POST['issued_to'] = $_SESSION[PBI_ID];
		$_POST[oi_no]=$_SESSION['initiate_hrm_sample_gift_requisition'];	
        $crud      =new crud($table_details);
        $crud->insert();
        $type=1;
        $msg='New Entry Successfully Inserted.';		

        unset($_POST);
        unset($$unique);
    }
    
    
//for modify..................................
if(isset($_POST['modify']))
{
	$sd=$_POST[oi_date]; 
    $_POST[oi_date]=date('Y-m-d' , strtotime($sd));
    $_POST['edit_at']=time();
    $_POST['edit_by']=$_SESSION['userid'];
	$sd=$_POST[oi_date]; 
    $_POST[oi_date]=date('Y-m-d' , strtotime($sd));
    $crud->update($unique);
    $type=1;    
}





if (isset($_POST['confirm'])){
mysqli_query($conn, "Update ".$table." set status='PENDING' where ".$unique."=".$_SESSION['initiate_hrm_sample_gift_requisition']."");
mysqli_query($conn, "Update ".$table_details." set status='PENDING' where ".$unique."=".$_SESSION['initiate_hrm_sample_gift_requisition']."");
								

$name=find_a_field('personnel_basic_info','PBI_NAME','PBI_ID='.$_SESSION[PBI_ID]);
$emailId=find_a_field('essential_info','ESS_CORPORATE_EMAIL','PBI_ID='.$recommended_by);
$emailIds=find_a_field('essential_info','ESS_CORPORATE_EMAIL','PBI_ID='.$authorised_person);
			$to = $emailId;
				$subject = "Requisition for Sample / Gift";
				$txt1 = "<p>Dear Sir,</p>				
				<p>A requisition for Sample / Gift is pending for your Recommendation/Authorization. Please enter Employee Access module to approve the requisition. </p>				
				<p>Requisition By- ".$name."</p>				
				<p><b><i>This EMAIL is automatically generated by ERP Software.</i></b></p>";				
				$txt=$txt1.$txt2.$tr;				
				$from = 'erp@icpbd.com';
				$headers = "";
    $headers .= "From: ERP Software<erp@".$_SERVER['SERVER_NAME']."> \r\n";
$headers .= "Reply-To:" . $from . "\r\n" ."X-Mailer: PHP/" . phpversion();
$headers .= 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";        
mail($to,$subject,$txt,$headers); 
unset($_SESSION['initiate_hrm_sample_gift_requisition']);
							}

//for Delete..................................
if(isset($_POST['cancel']))
{   $crud = new crud($table);
    $condition=$unique."=".$_SESSION['initiate_hrm_sample_gift_requisition'];
    $crud->delete($condition);
    $crud = new crud($table_details);
    $condition = $unique . "=" . $_SESSION['initiate_hrm_sample_gift_requisition'];
    $crud->delete_all($condition);
    unset($_SESSION['initiate_hrm_sample_gift_requisition']);
}}

if (isset($_GET[id])) {
    $edit_value=find_all_field(''.$table_details.'','','id='.$_GET[id].'');
}

if(isset($_SESSION[initiate_hrm_sample_gift_requisition]))
{   $condition=$unique."=".$_SESSION[initiate_hrm_sample_gift_requisition];
    $data=db_fetch_object($table,$condition);
    while (list($key, $value)=each($data))
    { $$key=$value;}}
	

	$sql_recommended_by="SELECT  p.PBI_ID,concat(p.PBI_ID_UNIQUE,' : ',p.PBI_NAME,' : ',d.DEPT_SHORT_NAME) FROM
    personnel_basic_info p,
    department d,
    essential_info e
     where
     p.PBI_JOB_STATUS in ('In Service') and
     p.PBI_DEPARTMENT=d.DEPT_ID	and
     p.PBI_ID=e.PBI_ID and
     e.ESS_JOB_LOCATION=1 group by p.PBI_ID
      order by p.PBI_NAME";
	$sql_authorised_person="SELECT  p.PBI_ID,concat(p.PBI_ID_UNIQUE,' : ',p.PBI_NAME,' : ',d.DEPT_SHORT_NAME) FROM
    personnel_basic_info p,
    department d,
    essential_info e
     where
     p.PBI_JOB_STATUS in ('In Service') and
     p.PBI_DEPARTMENT=d.DEPT_ID	and
     p.PBI_ID=e.PBI_ID and
     e.ESS_JOB_LOCATION=1 group by p.PBI_ID
      order by p.PBI_NAME";

$items="SELECT i.item_id,concat(i.item_id,' : ',i.finish_goods_code,' : ',i.item_name) as item_name FROM  item_info i 
WHERE 
i.product_nature not in ('Salable') 
group by i.item_id order by i.item_id ";	

$rs="Select d.id,concat(i.item_id,' : ',i.finish_goods_code,' : ',i.item_name) as item_name,i.unit_name,d.qty
from 
".$table_details." d,
item_info i
  where 
 d.item_id=i.item_id and 
 d.".$unique."='".$_SESSION['initiate_hrm_sample_gift_requisition']."'
 ";
 $query=mysqli_query($conn, $re);
 while($data=mysqli_fetch_object($query)){
 if(isset($_POST['deletedata'.$data->id]))
  {  mysqli_query($conn, ("DELETE FROM ".$table_details." WHERE id=".$data->id));
      unset($_POST);}
  if(isset($_POST['editdata'.$data->id]))
  {   mysqli_query($conn, ("UPDATE ".$table_details." SET item_id='".$_POST[item_id]."', qty='".$_POST[qty]."' WHERE id=".$data->id));
      unset($_POST);
    }}
 						  
$COUNT_details_data=find_a_field(''.$table_details.'','Count(id)',''.$unique.'='.$_SESSION['initiate_hrm_sample_gift_requisition'].'');							  
?>

<?php require_once 'header_content.php'; ?>

<SCRIPT language=JavaScript>
function reload(form){
	var val=form.item_id.options[form.item_id.options.selectedIndex].value;
	self.location='<?=$page;?>?item_code_GET=' + val ;}
</script>
<style>
    input[type=text]{
        font-size: 11px;
    }
</style>
<?php require_once 'body_content.php'; ?>




                    <div class="col-md-12 col-xs-12">
                        <div class="x_panel">
                            <div class="x_title">
                                <h2><?=$title;?></h2>
                                <div class="clearfix"></div>
                            </div>
                            
                            
                            <div class="x_content"> 
                            <form action="" enctype="multipart/form-data" style="font-size:11px" method="post" name="addem" id="addem" >
                                 <? //require_once 'support_html.php';?>
                                     <table style="width:100%"  cellpadding="0" cellspacing="0">
                                        <tr>
                                            <td style="width:50%;">
                                            <div class="form-group">                                            
                                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">Requisition* No<span class="required">*</span>
                                                    </label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                                        <input type="text" id="<?=$unique?>"   required="required" name="<?=$unique?>" value="<? if($_SESSION['initiate_hrm_sample_gift_requisition']>0) { echo  $_SESSION['initiate_hrm_sample_gift_requisition']; 
											
														} else 
											
											{ echo find_a_field($table,'max('.$unique.')+1','1');											
											if($$unique<1) $$unique = 1;}?>" class="form-control col-md-7 col-xs-12"  readonly style="width:100%">
                                                    </div>
                                                </div></td>


                                            <td style="width:50%">
                                            <div class="form-group" style="width: 100%">
                                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">Date<span class="required">*</span></label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input type="date" MAX="<?=date('Y-m-d');?>" min="<?=date('Y-m-d', strtotime($date .' -'.find_a_field('acc_voucher_config','back_date_limit','1'). 'day'));?>" required="required" name="oi_date" value="<?=($oi_date!='')? $oi_date : date('Y-m-d') ?>" class="form-control col-md-7 col-xs-12" style="width:100%;font-size:11px" >      </div>
                                                </div>
                                            </td></tr>
                                            
                                            
                                            
                                            
   <tr><td style="height:5px"></td></tr>
<tr>
                                            <td><div class="form-group">
                                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name" style="width: 40%">Requisition Type<span class="required">*</span></label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12"><select style="width: 100%" class="select2_single form-control" name="req_type" id="req_type">
                      <option></option>
                      <option value="Budgeted" <?php if ($req_type=='Budgeted') echo 'selected'; else echo '';?> >Budgeted</option>
                      <option value="Non-Budgeted" <?php if ($req_type=='Non-Budgeted') echo 'selected'; else echo '';?>>Non-Budgeted</option>
                      </select> </div></div></td>
                                                    
                                                    

                                            <td><div class="form-group">
               <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name" style="width: 40%">Requisition Category<span class="required">*</span></label>
                 <div class="col-md-6 col-sm-6 col-xs-12">
                 <select style="width: 100%" class="select2_single form-control" name="requisition_cetegory" id="requisition_cetegory">
                <option></option>
                      <option value="Sample" <?php if ($requisition_cetegory=='Sample') echo 'selected'; else echo '';?> >Sample</option>
                      <option value="Gift" <?php if ($requisition_cetegory=='Gift') echo 'selected'; else echo '';?>>High</option>
                      </select></div></div></td>
                                        </tr>                                         
                                            
                                            
<tr><td style="height:5px"></td></tr>
<tr>
                                            <td><div class="form-group">
                                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name" style="width: 40%">By When Goods Required (Date)<span class="required">*</span></label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input type="date" id="by_when_date"  name="by_when_date" class="form-control col-md-7 col-xs-12" value="<?=$uncheckrow[by_when_date];?>" style="width:100%; font-size:11px" >
                                                    </div></div></td>
                                                    
                                                    

                                            <td><div class="form-group">
               <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name" style="width: 40%">By When Goods Required(Time)<span class="required">*</span></label>
                 <div class="col-md-6 col-sm-6 col-xs-12">
                 <input type="text" id="by_when_time"  name="by_when_time" class="form-control col-md-7 col-xs-12" value="<?=$by_when_time;?>" style="width:100%" ></div></div></td>
                                        </tr>                                       
                                            
                                            
                                            

<tr><td style="height:5px"></td></tr>
<tr>
                                            <td><div class="form-group">
                                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name" style="width: 40%">Priority<span class="required">*</span></label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12"><select style="width: 100%" class="select2_single form-control" name="Priority" id="Priority">
                      <option></option>
                      <option value="Urgent" <?php if ($Priority=='Urgent') echo 'selected'; else echo '';?> >Urgent</option>
                      <option value="High" <?php if ($Priority=='High') echo 'selected'; else echo '';?>>High</option>
                      <option value="Medium" <?php if ($Priority=='Medium') echo 'selected'; else echo '';?>>Medium</option>
                      <option value="Low" <?php if ($Priority=='Low') echo 'selected'; else echo '';?>>Low</option>                      
                      </select>
                                                    </div></div></td>
                                                    
                                                    

                                            <td><div class="form-group">
               <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name" style="width: 40%">Remarks<span class="required">*</span></label>
                 <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="text" name="oi_subject" id="oi_subject" value="<?=$oi_subject?>" class="form-control col-md-7 col-xs-12" style="width: 100%;"></div></div></td>
                                        </tr>

<tr><td style="height:5px"></td></tr>
                                    <tr>
                                    <td>
                                    <div class="form-group">
          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width:40%">Recommended By<span class="required">*</span></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
           <select style="width: 100%" class="select2_single form-control" name="recommended_by" id="recommended_by">
                      <option></option>                      
                      <?=advance_foreign_relation($sql_recommended_by,$recommended_by);?>
                      </select>
                      </div></div>
                      </td>
                                        
                                        
                                                                          
                                    <td>
                                    <div class="form-group">
         <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width:40%">Authorised By<span class="required">*</span></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
           <select style="width: 100%;" class="select2_single form-control" name="authorised_person" id="authorised_person">
                      <option></option>
                      <?=advance_foreign_relation($sql_recommended_by,$authorised_person);?>
                      </select>
                      </div></div>
                      </td>
                                    </tr>

                                        </table>











                                    <div class="form-group" style="margin-left:40%; margin-top: 15px">

                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <?php if($_SESSION[initiate_hrm_sample_gift_requisition]){  ?>
                                               <button type="submit" name="modify" class="btn btn-primary" onclick='return window.confirm("Are you confirm to Update?");' style="font-size:12px;">Update <?=$title;?></button>
                                                
                                                
                                                <!--button type="submit" name="delete" id="delete" class="btn btn-danger" onclick='return window.confirm("Are you confirm to Update?");'>Deleted</button-->

                                            <?php   } else {?>
                                                <button type="submit" name="initiate" onclick='return window.confirm("Are you confirm?");' class="btn btn-primary" style="font-size:12px;">Initiate <?=$title;?></button>
                                            <?php } ?>
                                        </div></div>
                                </form></div></div></div>











                    <?php if($_SESSION[initiate_hrm_sample_gift_requisition]):  ?>

                    
                                <form action="<?=$page?>" enctype="multipart/form-data" style="font-size:11px" name="addem" id="addem" class="form-horizontal form-label-left" method="post">
                                <? require_once 'support_html.php';?>
                                <input type="hidden" name="oi_date" id="oi_date" value="<?=$oi_date;?>"  />
                                <table align="center" style="width:98%; font-size: 11px" class="table table-striped table-bordered">
                                <thead>
                                <tr style="background-color: bisque">
                                <th style="text-align: center">Finish Goods Code</th>
                                <th style="text-align: center">Unit</th>
                                <th style="text-align: center">Request Qty</th>
                                <th style="text-align: center">Action</th></tr></thead>
                                <tbody>
                                <tr>
                                <td style="vertical-align: middle">
                                <select class="select2_single form-control" style="width:99%; font-size:11px" tabindex="-1" required="required"  id="item_id" name="item_id" onchange="javascript:reload(this.form)">
                                <option></option>
                                <? advance_foreign_relation(find_all_item($product_nature="'Salable','Both'"),($_GET[item_code_GET]>0)? $_GET[item_code_GET] : $edit_value->item_id);?>
                                </select></td>
                                <td style="vertical-align: middle; text-align:center"><?php if (isset($_GET[id])) : ?><?=find_a_field('item_info','unit_name','item_id='.$edit_value->item_id);?> <?php else: $item_all->unit_name; endif;?></td>
                                <td align="center" style="width:10%; vertical-align: middle">
                                <input type="text" id="qty" style="width:150px; height:37px; font-size: 11px; text-align:center"  value="<?=$edit_value->qty?>"  name="qty" class="form-control col-md-7 col-xs-12" placeholder="request qty"></td></td>
                                <td align="center" style="width:5%; vertical-align: middle">
                                <?php if (isset($_GET[id])) : ?><button type="submit" class="btn btn-primary" name="editdata<?=$_GET[id];?>" id="editdata<?=$_GET[id];?>" style="font-size: 11px">Update</button><br><a href="<?=$page;?>" style="font-size: 11px"  onclick='return window.confirm("Mr. <?php echo $_SESSION["username"]; ?>, Are you sure you want to Delete the Voucher?");' class="btn btn-danger">Cancel</a>
                                <?php else: ?><button type="submit" class="btn btn-primary" name="add" id="add" style="font-size: 11px">Add</button> <?php endif; ?></td>
                                </table></form>
<?=added_data_delete_edit($rs,$unique,$unique_GET,$COUNT_details_data);
endif;?>
<?=$html->footer_content();mysqli_close($conn);?>