 <?php
require_once 'support_file.php';
$title="FG Purchase Requisition";

$dfrom=date('Y-1-1');
$dto=date('Y-m-d');

$now=time();

$table="purchase_fg_employee";
$unique = 'oi_no';   // Primary Key of this Database table
$table_deatils = 'purchase_fg_employee_details';
$details_unique = 'id';
$page="hrm_requisition_fg_purchase.php";
$crud      =new crud($table);
$taken=getSVALUE("".$table_deatils."", "SUM(qty)", " where oi_date between '$dfrom' and '$dto' and status not in ('MANUAL') and  issued_to='".$_SESSION[PBI_ID]."' and item_id=".$_GET[item_code_GET]."");
$unit=getSVALUE("item_info", "unit_name", " where item_id=".$_GET[item_code_GET]."");
$department=getSVALUE("personnel_basic_info", "PBI_DEPARTMENT", " where PBI_ID=".$_SESSION[PBI_ID]."");
$targeturl="<meta http-equiv='refresh' content='0;$page'>";

if(prevent_multi_submit()){
   
    if(isset($_POST['initiate']))
    {		
		
		
		$_POST['section_id'] = $_SESSION['sectionid'];
		$_POST['company_id'] = $_SESSION['companyid'];
		$_POST['entry_by'] = $_SESSION['userid'];
        $_POST['entry_at'] = date('Y-m-d H:s:i');
		$sd=$_POST[oi_date]; 
		$_POST[oi_date]=date('Y-m-d' , strtotime($sd));
		$bhd=$_POST[by_when_date]; 
		$_POST[by_when_date]=date('Y-m-d' , strtotime($bhd));
		$_POST['issue_type'] = 'Office Issue';
	    $_POST['status'] = 'MANUAL';
		$_POST['requisition_from'] = $department;
	    $_POST['warehouse_id'] = '11';
		$_POST['issued_to'] = $_SESSION[PBI_ID];
		$_SESSION['initiate_hrm_fg_purchase_requisition']=$_POST[$unique];
        $crud->insert();
        $type=1;
        $msg='New Entry Successfully Inserted.';

        unset($_POST);
        unset($$unique);
    }
	
	
	if(isset($_POST['add']))
    {			
		
		$_POST['entry_by'] = $_SESSION['userid'];
        $_POST['entry_at'] = date('Y-m-d H:s:i');
		$sd=$_POST[oi_date]; 
		$_POST[oi_date]=date('Y-m-d' , strtotime($sd));		
	    $_POST['issue_type'] = 'Office Issue';	
	    $_POST['status'] = 'MANUAL';
		$_POST['requisition_from'] = $_SESSION["department"];
	    $_POST['warehouse_id'] = '11';
		$_POST['recommend_qty'] = $_POST['qty'];
        $_POST['amount'] = $_POST['qty']*$_POST['rate'];
		$_POST['request_qty'] = $_POST['qty'];
		$_POST['issued_to'] = $_SESSION[PBI_ID];
		$_POST[oi_no]=$_SESSION['initiate_hrm_fg_purchase_requisition'];
        $crud      =new crud($table_deatils);
        $crud->insert();
        $type=1;
        $msg='New Entry Successfully Inserted.';		

        unset($_POST);
        unset($$unique);
    }
    
    
//for modify..................................
if(isset($_POST['modify']))
{
	$sd=$_POST[oi_date]; 
    $_POST[oi_date]=date('Y-m-d' , strtotime($sd));
    $_POST['edit_at']=time();
    $_POST['edit_by']=$_SESSION['userid'];
	$sd=$_POST[oi_date]; 
    $_POST[oi_date]=date('Y-m-d' , strtotime($sd));
    $crud->update($unique);
    $type=1;    
}





if (isset($_POST['confirmsave'])){
mysql_query("Update ".$table." set status='PENDING' where ".$unique."=".$_SESSION['initiate_hrm_fg_purchase_requisition']."");
mysql_query("Update ".$table_deatils." set status='PENDING' where ".$unique."=".$_SESSION['initiate_hrm_fg_purchase_requisition']."");
								

$name=find_a_field('personnel_basic_info','PBI_NAME','PBI_ID='.$_SESSION[PBI_ID]);
$emailId=find_a_field('essential_info','ESS_CORPORATE_EMAIL','PBI_ID='.$recommended_by);
$emailIds=find_a_field('essential_info','ESS_CORPORATE_EMAIL','PBI_ID='.$authorised_person);
			$to = $emailId;
				$subject = "Requisition for FG Purchased";
				$txt1 = "<p>Dear Sir,</p>				
				<p>A requisition for FG Purchased is pending for your Recommendation/Authorization. Please enter Employee Access module to approve the requisition. </p>				
				<p>Requisition By- ".$name."</p>				
				<p><b><i>This EMAIL is automatically generated by ERP Software.</i></b></p>";				
				$txt=$txt1.$txt2.$tr;				
				$from = 'erp@icpbd.com';
				$headers = "";
$headers .= "From: ERP Software<erp@".$_SERVER['SERVER_NAME']."> \r\n";
$headers .= "Reply-To:" . $from . "\r\n" ."X-Mailer: PHP/" . phpversion();
$headers .= 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";        
mail($to,$subject,$txt,$headers);

unset($_SESSION['initiate_hrm_fg_purchase_requisition']);
							}

//for Delete..................................
if(isset($_POST['deleted']))
{   $crud = new crud($table_deatils);
    $condition =$unique."=".$_SESSION['initiate_hrm_fg_purchase_requisition'];
    $crud->delete_all($condition);
    $crud = new crud($table);
    $condition=$unique."=".$_SESSION['initiate_hrm_fg_purchase_requisition'];
    $crud->delete($condition);
    unset($_SESSION['initiate_hrm_fg_purchase_requisition']);
    echo $targeturl;
}}

// data query..................................
if(isset($_SESSION[initiate_hrm_fg_purchase_requisition]))
{   $condition=$unique."=".$_SESSION[initiate_hrm_fg_purchase_requisition];
    $data=db_fetch_object($table,$condition);
    while (list($key, $value)=each($data))
    { $$key=$value;}}

 $result=mysqli_query($conn,"SELECT  p.*,d.* FROM 
							 
							personnel_basic_info p,
							department d
							 where 
							 p.PBI_JOB_STATUS in ('In Service') and 							 
							 p.PBI_DEPARTMENT=d.DEPT_ID					 
							  order by p.PBI_NAME");
?>

<?php require_once 'header_content.php'; ?>

<SCRIPT language=JavaScript>
function reload(form){
	var val=form.item_id.options[form.item_id.options.selectedIndex].value;
	self.location='<?=$page;?>?item_code_GET=' + val ;}
</script>
 <style>
     input[type=text]{
         font-size: 11px;
     }
 </style>

<?php require_once 'body_content.php'; ?>




                    <div class="col-md-12 col-xs-12">
                        <div class="x_panel">
                            <div class="x_title">
                                <h2><?php echo $title; ?></h2>
                                <ul class="nav navbar-right panel_toolbox">
                                    <div class="input-group pull-right">
                                        </div>
                                </ul>
                                <div class="clearfix"></div>
                            </div>
                            
                            
                            <div class="x_content"> 
                            <form action="" enctype="multipart/form-data" method="post" name="addem" id="addem" style="font-size: 11px">
                                 <? //require_once 'support_html.php';?>
                                     <table style="width:100%"  cellpadding="0" cellspacing="0">
                                        <tr>
                                            <td style="width:50%;">
                                            <div class="form-group">                                            
                                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">Requisition* No<span class="required">*</span>
                                                    </label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                                        <input type="text" id="<?=$unique?>"   required="required" name="<?=$unique?>" value="<? if($_SESSION['initiate_hrm_fg_purchase_requisition']>0) { echo  $_SESSION['initiate_hrm_fg_purchase_requisition']; 
											
														} else 
											
											{ echo find_a_field($table,'max('.$unique.')+1','1');											
											if($$unique<1) $$unique = 1;}?>" class="form-control col-md-7 col-xs-12"  readonly style="width:100%">
                                                    </div>
                                                </div></td>


                                            <td style="width:50%">
                                            <div class="form-group" style="width: 100%">
                                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">Requisition Date<span class="required">*</span></label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input type="text" id="oi_date" readonly  required="required" name="oi_date" value="<?php if($_SESSION[initiate_hrm_fg_purchase_requisition]>0){ echo date('m/d/y' , strtotime($oi_date)); } else { echo ''; } ?>" class="form-control col-md-7 col-xs-12" style="width:100%" >      </div>
                                                </div>
                                            </td></tr>
                                            
                                            
                                            
                                            
   <tr><td style="height:5px"></td></tr>
<tr>
                                            <td><div class="form-group">
                                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name" style="width: 40%">Payment Type<span class="required">*</span></label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12"><select style="width: 100%" class="select2_single form-control" name="req_category" id="req_category">
                      <option></option>
                      <option value="Credit" <?php if ($req_category=='Credit') echo 'selected'; else echo '';?> >Credit</option>
                      <option value="Cash" <?php if ($req_category=='Cash') echo 'selected'; else echo '';?>>Cash</option>
                      </select> </div></div></td>
                                                    
                                                    

                                            <td><div class="form-group">
                                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name" style="width: 40%">By When Goods Required (Date)<span class="required">*</span></label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                                        <input type="text" id="by_when_date"  name="by_when_date" class="form-control col-md-7 col-xs-12" value="<?php if($_SESSION[initiate_hrm_fg_purchase_requisition]>0){ echo date('m/d/y' , strtotime($uncheckrow[by_when_date])); } else { echo ''; } ?>" style="width:100%" >
                                                    </div></div></td>
                                        </tr>
<tr><td style="height:5px"></td></tr>
<tr>
                                            <td><div class="form-group">
                                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name" style="width: 40%">Priority<span class="required">*</span></label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12"><select style="width: 100%" class="select2_single form-control" name="Priority" id="Priority">
                      <option></option>
                      <option value="Urgent" <?php if ($Priority=='Urgent') echo 'selected'; else echo '';?> >Urgent</option>
                      <option value="High" <?php if ($Priority=='High') echo 'selected'; else echo '';?>>High</option>
                      <option value="Medium" <?php if ($Priority=='Medium') echo 'selected'; else echo '';?>>Medium</option>
                      <option value="Low" <?php if ($Priority=='Low') echo 'selected'; else echo '';?>>Low</option>                      
                      </select>
                                                    </div></div></td>
                                                    
                                                    

                                            <td><div class="form-group">
               <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name" style="width: 40%">Remarks<span class="required">*</span></label>
                 <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="text" name="oi_subject" id="oi_subject" value="<?=$oi_subject?>" class="form-control col-md-7 col-xs-12" style="width: 100%;"></div></div></td>
                                        </tr>

<tr><td style="height:5px"></td></tr>
                                    <tr>
                                    <td>
                                    <div class="form-group">
          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width:40%">Recommended By<span class="required">*</span></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
           <select style="width: 100%" class="select2_single form-control" name="recommended_by" id="recommended_by">
                      <option></option>
                      <? foreign_relation('personnel_basic_info','PBI_ID','PBI_NAME',$recommended_by,' 1');?></select>
                                        </div></div> 
                                        </td>
                                        
                                        
                                                                          
                                    <td>
                                    <div class="form-group">
         <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width:40%">Authorised By<span class="required">*</span></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
           <select style="width: 100%;" class="select2_single form-control" name="authorised_person" id="authorised_person">
                      <option></option>
                     <? foreign_relation('personnel_basic_info','PBI_ID','PBI_NAME',$authorised_person,' 1');?>
                      </select>
                                    </div></div>
                                    </td>
                                    </tr>

                                        </table>











                                    <div class="form-group" style="margin-left:40%; margin-top: 15px">
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <?php if($_SESSION[initiate_hrm_fg_purchase_requisition]){  ?>
                                               <button type="submit" name="modify" class="btn btn-primary" onclick='return window.confirm("Are you confirm to Update?");' style="font-size: 11px">Update <?=$title;?></button>
                                            <?php   } else {?>
                                                <button type="submit" name="initiate" onclick='return window.confirm("Are you confirm?");' class="btn btn-primary" style="font-size: 11px">Initiate <?=$title;?></button>
                                            <?php } ?>
                                        </div></div>
                                </form></div></div></div>











                    <?php if($_SESSION[initiate_hrm_fg_purchase_requisition]){  ?>

                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="x_panel">
                            <div class="x_content">
                                <form action="" enctype="multipart/form-data" name="addem" id="addem" class="form-horizontal form-label-left" method="post"><? require_once 'support_html.php';?>
                                    <table style="width:100%">
                                        <tbody>
                                        <tr>
                                            <td align="left" style="width: 25%">
                                            <input type="hidden" name="oi_date" id="oi_date" value="<?=$oi_date;?>"  />
      <select class="select2_single form-control" style="width:350px" tabindex="-1" required="required"  id="item_id" name="item_id" onchange="javascript:reload(this.form)">
                            <option></option>
                            
                            <?php 														
							$result=mysqli_query($conn, "SELECT i.*,sg.*,g.* FROM 							
							item_info i,
							item_sub_group sg,
							item_group g
							 where 
							 i.sub_group_id=sg.sub_group_id and 
							 sg.group_id=g.group_id and 
							 g.group_id  in ('500000000') 							 
							  order by i.item_name");
							while($row=mysqli_fetch_array($result)){  ?>
                  <option  value="<?php echo $row[item_id]; ?>" <?php if($_GET[item_code_GET]==$row[item_id]) echo 'selected' ?>><?php echo $row[item_id]; ?>-<?php echo $row[item_name]; ?> (<?php echo $row[sub_group_name]; ?>)</option>
                    <?php } ?>
                          </select></td>
                                           
                                               <td style="width:10%" align="center">
     <input type="hidden" id="taken" name="taken" value="<?=$taken;?>" > 
      <input type="text" id="takens" style="width:200px; height:37px; font-size: 12px; text-align:center"    name="takens" class="form-control col-md-7 col-xs-12" value="Has Taken (Current Year): <?=$taken;?>, <?=$unit;?>" readonly > </td>

                                            <td align="center" style="width:8%">
                                                <input type="text" id="rate" style="width:100px; height:37px; font-size: 12px; text-align:center"  readonly value="<?=$rate=getSVALUE("item_info", "d_price", " where item_id=".$_GET[item_code_GET]."");?>"   name="rate" class="form-control col-md-7 col-xs-12" ></td>

                                            <td align="center" style="width:8%">
                                                 <input type="text" id="qty" style="width:100px; height:37px; font-size: 12px; text-align:center"    name="qty" class="form-control col-md-7 col-xs-12" placeholder="qty"></td>
                                            <td align="center" style="width:5%"><button type="submit" class="btn btn-primary" name="add" id="add">Add to Cart</button></td></tr>
                                            </tbody>
                                    </table>
                                    <input name="count" id="count" type="hidden" value="" />
                                </form>
                            </div></div></div></div>


                <!-----------------------Data Save Confirm ------------------------------------------------------------------------->

              
                <form id="ismail" name="ismail"  method="post"  class="form-horizontal form-label-left">
                    <input type="hidden" name="recommended_by" id="recommended_by" value="<?=$recommended_by;?>">
                    <input type="hidden" name="authorised_person" id="authorised_person" value="<?=$authorised_person;?>">
                    <table  class="table table-striped table-bordered" style="width:100%">
                        <thead>
                        <tr>
                            <th>SL</th>
                            <th>Item Description</th>
                             <th style="text-align:center">Unit Name</th>
                            <th style="text-align:center">Qty</th>
                            <th style="text-align:center">Rate</th>
                            <th style="text-align:center">Amount</th>
                            <th style="width:15%; text-align:center">Action</th>

                        </tr>
                        </thead>
                        <tbody>
                        <?php
                     
                        $rs=mysql_query("Select 
d.*,i.*
from 
".$table_deatils." d,
item_info i
  where 
 d.item_id=i.item_id and 
 d.".$unique."='".$_SESSION['initiate_hrm_fg_purchase_requisition']."'
 ");
                        while($uncheckrow=mysql_fetch_array($rs)){
                            $js=$js+1;
                            $ids=$uncheckrow[id];
                            $item_id_update=$_POST['item_id_update'.$ids];
                            $upcr_qty=$_POST['upcr_qty'.$ids];
                            $upcr_rate=$_POST['upcr_rate'.$ids];
                            $amount_up=$upcr_qty*$upcr_rate;


                            if(isset($_POST['deletedata'.$ids]))
                            {
                                mysql_query("DELETE FROM ".$table_deatils." WHERE id='$ids'"); ?>
                                <meta http-equiv="refresh" content="0;<?=$page?>">
                                <?php
                            }

                            if(isset($_POST['editdata'.$ids]))
                            {
                                mysql_query("Update ".$table_deatils." set item_id='$item_id_update',qty='$upcr_qty',recommend_qty='$upcr_qty',request_qty='$upcr_qty',amount='$amount_up' WHERE id='$ids'"); ?>
                                <meta http-equiv="refresh" content="0;<?=$page?>">
                            <?php }?>


                            <tr>
                                <td style="width:3%; vertical-align:middle"><?php echo $js; ?></td>
                                <td style="vertical-align:middle">
<select class="select2_single form-control" style="width:300px" tabindex="-1" required="required" id="item_id_update<?php echo $ids; ?>"   name="item_id_update<?php echo $ids; ?>">
                                    <?php 														
							$result=mysql_query("SELECT i.*,sg.*,g.* FROM 							
							item_info i,
							item_sub_group sg,
							item_group g
							 where 
							 i.sub_group_id=sg.sub_group_id and 
							 sg.group_id=g.group_id and 
							 g.group_id  in ('500000000') 							 
							  order by i.item_name");
							while($row=mysql_fetch_array($result)){  ?>
                  <option  value="<?php echo $row[item_id]; ?>" <?php if($uncheckrow[item_id]==$row[item_id]) echo 'selected' ?>><?php echo $row[item_id]; ?>-<?php echo $row[item_name]; ?> (<?php echo $row[sub_group_name]; ?>)</option>
                    <?php } ?>
                          </select></td>
                          <td style="text-align:center"><?=$unit=getSVALUE("item_info", "unit_name", " where item_id=".$uncheckrow[item_id]."");?></td>


                                <td align="center" style="text-align:center">
                                    <input type="hidden" id="upcr_rate<?php echo $ids; ?>" style="width:130px; margin-left:1%; height:37px; font-weight:bold; text-align:center; float:none"    name="upcr_rate<?php echo $ids; ?>"  value="<?=$uncheckrow[rate] ;?>"  autocomplete="off"  >
                                    <input type="text" id="upcr_qty<?php echo $ids; ?>" style="width:130px; margin-left:1%; height:37px; font-weight:bold; text-align:center; float:none"    name="upcr_qty<?php echo $ids; ?>"  value="<?=$uncheckrow[qty] ;?>" class="form-control col-md-7 col-xs-12" autocomplete="off"  ></td>

                                <td align="center" style="text-align:center"><?=$uncheckrow[rate] ;?></td>
                                <td align="center" style="text-align:center"><?=number_format($uncheckrow[amount],2) ;?></td>



                                <td align="center" style="width:10%;vertical-align:middle">
                                    <button type="submit" name="editdata<?php echo $ids; ?>" style="background-color:transparent; border:none" onclick='return window.confirm("Mr. <?php echo $_SESSION["username"]; ?>, Are you sure you want to Edit Date?");'><img src="update.jpg" style="width:20px;  height:20px"></button>
                                    <button type="submit" name="deletedata<?php echo $ids; ?>" style="background-color:transparent; border:none" onclick='return window.confirm("Mr. <?php echo $_SESSION["username"]; ?>, Are you sure you want to Delete Credit Voucher?");'><img src="delete.png" style="width:20px;  height:18px"></button>
                                </td>

                            </tr> 
							<?php
                        $total_amount=$total_amount+$uncheckrow[amount];
                        } ?>
                        </tbody>

                        <tr style="font-weight: bold"><td colspan="5" style="text-align: right">Total Amount</td><td style="text-align: center"><?=number_format($total_amount,2)?></td><td></td></tr>
                    </table>


                        <table   style="width:100%">

                       <tr>
                            <td colspan="9" style="text-align:center">
                                <?php
                                if(isset($_POST[cancel])){
                                    $deletes=mysql_query("Delete From ".$table." where ".$unique."='$_SESSION[initiate_hrm_fg_purchase_requisition]' and section_id='$_SESSION[sectionid]' and company_id='$_SESSION[companyid]'");
                                    $deletes=mysql_query("Delete From ".$table_deatils." where ".$unique."='$_SESSION[initiate_hrm_fg_purchase_requisition]' and section_id='$_SESSION[sectionid]' and company_id='$_SESSION[companyid]'");
                                    unset($_SESSION["initiate_hrm_fg_purchase_requisition"]); ?>
                                    <meta http-equiv="refresh" content="0;<?=$page;?>">
                                <?php } ?>
                                <button type="submit" style="float: left" name="deleted" id="deleted" onclick='return window.confirm("Mr. <?php echo $_SESSION["username"]; ?>, Are you sure you want to Delete the requisition?");' class="btn btn-danger">Delete the <?=$title;?> </button>
                                
                                    <button type="submit" style="float: right" type="submit" onclick='return window.confirm("Mr. <?php echo $_SESSION["username"]; ?>, Are you sure you want to Delete the requisition?");' name="confirmsave" class="btn btn-success">Confirm and Finish <?=$title;?> </button>
                                


                            </td></tr></table></form>
    <?php } ?>
<?php require_once 'footer_content.php' ?>
<script>
    $(document).ready(function() {
        $('#oi_date').daterangepicker({

            singleDatePicker: true,
            calender_style: "picker_4",

        }, function(start, end, label) {
            console.log(start.toISOString(), end.toISOString(), label);
        });
    });
</script>


<script>
    $(document).ready(function() {
        $('#by_when_date').daterangepicker({

            singleDatePicker: true,
            calender_style: "picker_4",

        }, function(start, end, label) {
            console.log(start.toISOString(), end.toISOString(), label);
        });
    });
</script>
