 <?php
require_once 'support_file.php';
$title="Handover / Takeover Application";

$dfrom=date('Y-1-1');
$dto=date('Y-m-d');

$now=time();

$table="handover_application_master";
$unique = 'handOver_id';   // Primary Key of this Database table
$table_deatils = 'handover_application_details';
$details_unique = 'id';
$page="hrm_requisition_handover_takeover.php";
$crud      =new crud($table);
$targeturl="<meta http-equiv='refresh' content='0;$page'>";

if(prevent_multi_submit()){
   
    if(isset($_POST['initiate']))
    {
		$_POST['section_id'] = $_SESSION['sectionid'];
		$_POST['company_id'] = $_SESSION['companyid'];
		$_POST['entry_by'] = $_SESSION['userid'];
        $_POST['entry_at'] = date('Y-m-d H:s:i');
		$sd=$_POST[oi_date]; 
		$_POST[oi_date]=date('Y-m-d' , strtotime($sd));
	    $_POST['issue_type'] = 'Office Issue';	
	    $_POST['status'] = 'MANUAL';
		$_POST['requisition_from'] = $department;
	    $_POST['warehouse_id'] = '11';
		$_POST['issued_to'] = $_SESSION[PBI_ID];
		$_SESSION['initiate_hrm_handover_takeover_requisition']=$_POST[$unique];
        $crud->insert();
        $type=1;
        $msg='New Entry Successfully Inserted.';
        unset($_POST);
        unset($$unique);
    }
	
	
	if(isset($_POST['add']))
    {			
		
		$_POST['entry_by'] = $_SESSION['userid'];
        $_POST['entry_at'] = date('Y-m-d H:s:i');
		$_POST['takeOver_department'] = find_a_field("department","DEPT_DESC","DEPT_ID=".$_POST['takeOver_department_ID']."");
		$_POST['request_qty'] = $_POST['qty'];
		$_POST['issued_to'] = $_SESSION[PBI_ID];
		$_POST[oi_no]=$_SESSION['initiate_hrm_handover_takeover_requisition'];	
        $crud      =new crud($table_deatils);
        $crud->insert();
        $type=1;
        $msg='New Entry Successfully Inserted.';		

        unset($_POST);
        unset($$unique);
    }
    
    
//for modify..................................
if(isset($_POST['modify']))
{
	$sd=$_POST[oi_date]; 
    $_POST[oi_date]=date('Y-m-d' , strtotime($sd));
    $_POST['edit_at']=time();
    $_POST['edit_by']=$_SESSION['userid'];
	$sd=$_POST[oi_date]; 
    $_POST[oi_date]=date('Y-m-d' , strtotime($sd));
    $crud->update($unique);
    $type=1;    
}





if (isset($_POST['confirmsave'])){
mysql_query("Update ".$table." set status='PENDING' where ".$unique."=".$_SESSION['initiate_hrm_handover_takeover_requisition']."");
mysql_query("Update ".$table_deatils." set takeOver_status='PENDING' where ".$unique."=".$_SESSION['initiate_hrm_handover_takeover_requisition']."");
								

$name=find_a_field('personnel_basic_info','PBI_NAME','PBI_ID='.$_SESSION[PBI_ID]);
$emailId=find_a_field('essential_info','ESS_CORPORATE_EMAIL','PBI_ID='.$recommended_by);
$emailIds=find_a_field('essential_info','ESS_CORPORATE_EMAIL','PBI_ID='.$authorised_person);
			$to = $emailId;
				$subject = "Handover / Takeover Application";
				$txt1 = "<p>Dear Sir,</p>				
				<p>A requisition for Sample / Gift is pending for your Recommendation/Authorization. Please enter Employee Access module to approve the requisition. </p>				
				<p>Requisition By- ".$name."</p>				
				<p><b><i>This EMAIL is automatically generated by ERP Software.</i></b></p>";				
				$txt=$txt1.$txt2.$tr;				
				$from = 'erp@icpbd.com';
				$headers = "";
    $headers .= "From: ERP Software<erp@".$_SERVER['SERVER_NAME']."> \r\n";
$headers .= "Reply-To:" . $from . "\r\n" ."X-Mailer: PHP/" . phpversion();
$headers .= 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";        
mail($to,$subject,$txt,$headers); 
unset($_SESSION['initiate_hrm_handover_takeover_requisition']);
							}

//for Delete..................................
if(isset($_POST['delete']))
{   $crud = new crud($table);
    $condition=$unique."=".$_SESSION['initiate_hrm_handover_takeover_requisition'];
    $crud->delete($condition);

    $crud = new crud($table_deatils);
    $condition = $unique . "=" . $_SESSION['initiate_hrm_handover_takeover_requisition'];
    $crud->delete_all($condition);
    unset($_SESSION['initiate_hrm_handover_takeover_requisition']);



    $msg='Successfully Deleted.';
    echo "<script>self.opener.location = '$page'; self.blur(); </script>";
    echo "<script>window.close(); </script>";
}}

// data query..................................
if(isset($_SESSION[initiate_hrm_handover_takeover_requisition]))
{   $condition=$unique."=".$_SESSION[initiate_hrm_handover_takeover_requisition];
    $data=db_fetch_object($table,$condition);
    while (list($key, $value)=each($data))
    { $$key=$value;}}
?>

<?php require_once 'header_content.php'; ?>

<SCRIPT language=JavaScript>
function reload(form){
	var val=form.takeOver_department_ID.options[form.takeOver_department_ID.options.selectedIndex].value;
	self.location='<?=$page;?>?takeOver_department_ID_GET=' + val ;}
</script>

<?php require_once 'body_content.php'; ?>




                    <div class="col-md-12 col-xs-12">
                        <div class="x_panel">
                            <div class="x_title">
                                <h2><?php echo $title; ?></h2>
                                <ul class="nav navbar-right panel_toolbox">
                                    <div class="input-group pull-right">
                                        </div>
                                </ul>
                                <div class="clearfix"></div>
                            </div>
                            
                            
                            <div class="x_content"> 
                            <form action="" enctype="multipart/form-data" method="post" name="addem" id="addem" >
                                 <? //require_once 'support_html.php';?>
                                     <table style="width:100%"  cellpadding="0" cellspacing="0">
                                        <tr>
                                            <td style="width:50%;">
                                            <div class="form-group">                                            
                                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">Application * No<span class="required">*</span>
                                                    </label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                                        <input type="text" id="<?=$unique?>"   required="required" name="<?=$unique?>" value="<? if($_SESSION['initiate_hrm_handover_takeover_requisition']>0) { echo  $_SESSION['initiate_hrm_handover_takeover_requisition']; 
											
														} else 
											
											{ echo find_a_field($table,'max('.$unique.')+1','1');											
											if($$unique<1) $$unique = 1;}?>" class="form-control col-md-7 col-xs-12"  readonly style="width:100%">
                                                    </div>
                                                </div></td>


                                            <td style="width:50%">
                                            <div class="form-group" style="width: 100%">
                                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">Application Date<span class="required">*</span></label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                                    <input type="text" id="oi_date" readonly  required="required" name="oi_date" value="<?php if($_SESSION[initiate_hrm_handover_takeover_requisition]>0){ echo date('m/d/y' , strtotime($oi_date)); } else { echo ''; } ?>" class="form-control col-md-7 col-xs-12" style="width:100%" >      </div>
                                                </div>
                                            </td></tr>
                                            
                                            
                                            
                                            
   <tr><td style="height:5px"></td></tr>
<tr>
                                            <td><div class="form-group">
                                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name" style="width: 40%">Reason for Handover :<span class="required">*</span></label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12"><select style="width: 100%" class="select2_single form-control" name="reason_for_handover" id="reason_for_handover">
                      <option></option>
                      <option value="Vocation" <?php if ($reason_for_handover=='Vocation') echo 'selected'; else echo '';?> >Vocation</option>
                      <option value="Transfer" <?php if ($reason_for_handover=='Transfer') echo 'selected'; else echo '';?>>Transfer</option>
                                                            <option value="End of Employment" <?php if ($reason_for_handover=='End of Employment') echo 'selected'; else echo '';?>>End of Employment</option>
                                                            <option value="Other" <?php if ($reason_for_handover=='Other') echo 'selected'; else echo '';?>>Other</option>
                      </select> </div></div></td>
                                                    
                                               <td><div class="form-group">
               <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name" style="width: 40%">Remarks<span class="required">*</span></label>
                 <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="text" name="oi_subject" id="oi_subject" value="<?=$oi_subject?>" class="form-control col-md-7 col-xs-12" style="width: 100%;"></div></div></td>
                                        </tr>
                                        </table>



                                    <div class="form-group" style="margin-left:40%; margin-top: 15px">
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <?php if($_SESSION[initiate_hrm_handover_takeover_requisition]){  ?>
                                               <button type="submit" name="modify" class="btn btn-success" onclick='return window.confirm("Are you confirm to Update?");'>Update <?=$title;?></button>
                                             <?php   } else {?>
                                                <button type="submit" name="initiate" onclick='return window.confirm("Are you confirm?");' class="btn btn-primary">Initiate <?=$title;?></button>
                                            <?php } ?>
                                        </div></div>
                                </form></div></div></div>











                    <?php if($_SESSION[initiate_hrm_handover_takeover_requisition]){  ?>

                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="x_panel">
                            <div class="x_content">
                                <form action="" enctype="multipart/form-data" name="addem" id="addem" class="form-horizontal form-label-left" method="post"><? require_once 'support_html.php';?>
                                    <table class="table table-striped table-bordered" style="width:100%">
                                        <thead>
                                        <tr>
                                            <th style="text-align: center; width: 350px">Department</th>
                                            <th style="text-align: center; width: 250px">Taken Over By</th>
                                            <th style="text-align: center">Details</th><th></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td align="left">
                                            <input type="hidden" name="oi_date" id="oi_date" value="<?=$oi_date;?>"  />
      <select class="select2_single form-control" style="width:350px" tabindex="-1" required="required"  id="takeOver_department_ID" name="takeOver_department_ID" onchange="javascript:reload(this.form)">
                            <option></option>
                            
                            <?php 														
							$result=mysql_query("SELECT d.* FROM 							
							department d
							 where 
							 1 order by d.DEPT_DESC");
							while($row=mysql_fetch_array($result)){  ?>
                  <option  value="<?php echo $row[DEPT_ID]; ?>" <?php if($_GET[takeOver_department_ID_GET]==$row[DEPT_ID]) echo 'selected' ?>><?php echo $row[DEPT_DESC]; ?></option>
                    <?php } ?>
                          </select></td>
                                           
                                               <td  align="center">
                                                   <select class="select2_single form-control" style="width: 250px" tabindex="-1" required="required"  id="takeOver_person" name="takeOver_person">
                                                       <option></option>
                                                       <?php
                                                       $result=mysql_query("SELECT p.* FROM 							
							personnel_basic_info p
							 where 
							 p.PBI_JOB_STATUS='In Service' and p.PBI_DEPARTMENT=".$_GET[takeOver_department_ID_GET]." and 
							 1 order by p.PBI_ID");
                                                       while($row=mysql_fetch_array($result)){  ?>
                                                           <option  value="<?php echo $row[PBI_ID]; ?>"><?php echo $row[PBI_ID_UNIQUE]; ?>-<?php echo $row[PBI_NAME]; ?></option>
                                                       <?php } ?>
                                                   </select></td>


                                            <td>
                                                <textarea id="takeOver_details" style="width: 100%"    name="takeOver_details" class="form-control col-md-7 col-xs-12"></textarea></td>
                                            <td align="center" style="width:5%"><button type="submit" class="btn btn-success" name="add" id="add">Add</button></td></tr>
                                            </tbody>
                                    </table>
                                </form>
                            </div></div></div></div>


                <!-----------------------Data Save Confirm ------------------------------------------------------------------------->

              
                <form id="ismail" name="ismail"  method="post"  class="form-horizontal form-label-left">
                    <table  class="table table-striped table-bordered" style="width:100%; font-size: 12px">
                        <thead>
                        <tr>
                            <th>SL</th>
                            <th>Department</th>
                             <th style="text-align:center">Taken Over By</th>
                            <th style="text-align:center">Details</th>
                            <th style="width:15%; text-align:center">Action</th>

                        </tr>
                        </thead>
                        <tbody>
                        <?php
                     
                        $rs=mysql_query("Select 
d.*,dep.*,p.*
from 
".$table_deatils." d,
department dep,
personnel_basic_info p
where 
 d.takeOver_department_ID=dep.DEPT_ID and 
 d.takeOver_person=p.PBI_ID and
 d.".$unique."='".$_SESSION['initiate_hrm_handover_takeover_requisition']."'
 ");
                        while($uncheckrow=mysql_fetch_array($rs)){
                            $js=$js+1;
                            $ids=$uncheckrow[id];
                            $item_id_update=$_POST['item_id_update'.$ids];
                            $upcr_qty=$_POST['upcr_qty'.$ids];
                            $upnarration=$_POST['upnarration'.$ids];


                            if(isset($_POST['deletedata'.$ids]))
                            {
                                mysql_query("DELETE FROM ".$table_deatils." WHERE id='$ids'"); ?>
                                <meta http-equiv="refresh" content="0;<?=$page?>">
                                <?php
                            }

                            if(isset($_POST['editdata'.$ids]))
                            { mysql_query("Update ".$table_deatils." set item_id='$item_id_update',qty='$upcr_qty',recommend_qty='$upcr_qty',request_qty='$upcr_qty' WHERE id='$ids'"); ?>
                                <meta http-equiv="refresh" content="0;<?=$page?>">
                            <?php }?>


                            <tr>
                                <td style="width:3%; vertical-align:middle"><?php echo $js; ?></td>
                                <td style="vertical-align:middle; width: 15%"><?=$DEPT_DESC=getSVALUE("department", "DEPT_DESC", " where DEPT_ID=".$uncheckrow[takeOver_department_ID]."");?></td>
                                <td style="vertical-align:middle; width: 25%"><?=$PBI_NAME=getSVALUE("personnel_basic_info", "PBI_NAME", " where PBI_ID=".$uncheckrow[takeOver_person]."");?></td>
                                <td align="center" style="text-align:center"><?=$uncheckrow[takeOver_details];?></td>

                                <td align="center" style="width:10%;vertical-align:middle">
                                    <button type="submit" name="deletedata<?php echo $ids; ?>" style="background-color:transparent; border:none" onclick='return window.confirm("Mr. <?php echo $_SESSION["username"]; ?>, Are you sure you want to Delete Credit Voucher?");'><img src="delete.png" style="width:15px;  height:15px"></button>
                                </td>

                            </tr> 
							<?php  } ?>
                             </tbody></table>

                    <?php
                                if(isset($_POST[cancel])){
                                    $deletes=mysql_query("Delete From ".$table." where ".$unique."='$_SESSION[initiate_hrm_handover_takeover_requisition]' and section_id='$_SESSION[sectionid]' and company_id='$_SESSION[companyid]'");
                                    $deletes=mysql_query("Delete From ".$table_deatils." where ".$unique."='$_SESSION[initiate_hrm_handover_takeover_requisition]' and section_id='$_SESSION[sectionid]' and company_id='$_SESSION[companyid]'");
                                    unset($_SESSION["initiate_hrm_handover_takeover_requisition"]); ?>
                                    <meta http-equiv="refresh" content="0;<?=$page;?>">
                                <?php } ?>
                                <button style="float: left" type="submit" name="cancel" onclick='return window.confirm("Mr. <?php echo $_SESSION["username"]; ?>, Are you want to Deleted?");' class="btn btn-danger">Delete</button>
                                <button style="float: right" type="submit" onclick='return window.confirm("Mr. <?php echo $_SESSION["username"]; ?>, Are you Confirm?");' name="confirmsave" class="btn btn-success">Confirm and Finish</button>
                              </form>
    <?php } ?>

<?php require_once 'footer_content.php' ?>
<script>
    $(document).ready(function() {
        $('#oi_date').daterangepicker({

            singleDatePicker: true,
            calender_style: "picker_4",

        }, function(start, end, label) {
            console.log(start.toISOString(), end.toISOString(), label);
        });
    });
</script>


<script>
    $(document).ready(function() {
        $('#by_when_date').daterangepicker({

            singleDatePicker: true,
            calender_style: "picker_4",

        }, function(start, end, label) {
            console.log(start.toISOString(), end.toISOString(), label);
        });
    });
</script>
