 <?php
require_once 'support_file.php';
$title="Un-Authorized Stationary Requisition";
$dfrom=date('Y-1-1');
$dto=date('Y-m-d');

$resultdets=mysqli_query($conn, "Select * from warehouse_other_issue where ".$unique."='".$_GET[$unique]."'") ;
$getid=mysqli_fetch_array($resultdets);
$dateTime = new DateTime('now', new DateTimeZone('Asia/Dhaka'));
$todayss=$dateTime->format("d/m/Y  h:i A");

$now=time();
$unique='oi_no';
$unique_field='oi_date';
$table="warehouse_other_issue";
$table_details="warehouse_other_issue_detail";
$current_status=find_a_field("".$table."","status","".$unique."=".$_GET[$unique]."");
$required_status="RECOMMENDED";
$authorused_status="UNCHECKED";
$page="hrm_unauthorised_requisition_stationary.php";
$crud      =new crud($table);
$$unique = $_GET[$unique];
$targeturl="<meta http-equiv='refresh' content='0;$page'>";

if(prevent_multi_submit()){
  
    if(isset($_POST['Return']))
    {		
    $_POST['status']='RETURNED';
	$_POST['return_comments']=$_POST['return_comments'];
	$_POST['recommended_date']=$todayss;	
    $crud->update($unique);
    $type=1;
	
	$chid=find_a_field('warehouse_other_issue','authorised_person',''.$unique.'='.$_GET[$unique]);
    $maild=find_a_field('essential_info','ESS_CORPORATE_EMAIL','PBI_ID='.$chid);
    $cby=find_a_field('warehouse_other_issue','issued_to','oi_no='.$_GET[$unique]);
	
	$to = $maild;
				$subject = "Stationary Requisition Returned!!";
				$txt = "<p>Dear Sir/Madam,</p>
				<p>Your Requisition has beed returned!!</b></p>
				<p>Returned Resone is : <b>".$_POST['return_comments']."<b></p>
				
				<p><i>This EMAIL is automatically generated by ERP Software.</i></p>";
				
				$from = 'erp@icpbd.com';
				$headers = "";
$headers .= "From: ERP Software<erp@".$_SERVER['SERVER_NAME']."> \r\n";
$headers .= "Reply-To:" . $from . "\r\n" ."X-Mailer: PHP/" . phpversion();
$headers .= 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";        
mail($to,$subject,$txt,$headers);
    //echo $targeturl;
    echo "<script>self.opener.location = '$page'; self.blur(); </script>";
    echo "<script>window.close(); </script>";
    }
    
    
//for modify..................................
if(isset($_POST['modify']))
{
    $_POST['edit_at']=time();
    $_POST['edit_by']=$_SESSION['userid'];
    $crud->update($unique);
    $type=1;
    //echo $targeturl;
    echo "<script>self.opener.location = '$page'; self.blur(); </script>";
    echo "<script>window.close(); </script>";
}

//for Delete..................................
if(isset($_POST['Deleted']))
{   $condition=$unique."=".$$unique;
    $crud->delete($condition);	
	$crud = new crud($table_details);
    $condition = $unique . "=" . $$unique;
    $crud->delete_all($condition);	
    unset($$unique);
    $type=1;
    $msg='Successfully Deleted.';
    echo "<script>self.opener.location = '$page'; self.blur(); </script>";
    echo "<script>window.close(); </script>";
}}

 if(isset($_POST[viewreport])) {
$res='select r.'.$unique.',r.'.$unique.' as Req_No,r.'.$unique_field.' as Req_Date,
				 (SELECT concat(p2.PBI_NAME," # ","(",de.DESG_SHORT_NAME,")") FROM 
							 
							personnel_basic_info p2,
							department d,
							designation de 
							 where 
							 p2.PBI_ID=r.issued_to and
							 p2.PBI_DESIGNATION=de.DESG_ID and  							 
							 p2.PBI_DEPARTMENT=d.DEPT_ID) as Req_By,r.oi_subject as Remarks,r.Priority,(select PBI_NAME from personnel_basic_info where PBI_ID=r.recommended_by) as recommended_by, recommended_date as recommended_at
				  from '.$table.' r
				  WHERE r.authorised_person='.$_SESSION['PBI_ID'].' and
				  r.req_category not in ("1500010000") and 	
				  
				  status="'.$required_status.'"				  
				   order by r.'.$unique.' DESC';
} else {
$res='select r.'.$unique.',r.'.$unique.' as Req_No,r.'.$unique_field.' as Req_Date,
				 (SELECT concat(p2.PBI_NAME," # ","(",de.DESG_SHORT_NAME,")") FROM 
							 
							personnel_basic_info p2,
							department d,
							designation de 
							 where 
							 p2.PBI_ID=r.issued_to and
							 p2.PBI_DESIGNATION=de.DESG_ID and  							 
							 p2.PBI_DEPARTMENT=d.DEPT_ID) as Req_By,r.oi_subject as Remarks,r.Priority,(select PBI_NAME from personnel_basic_info where PBI_ID=r.recommended_by) as recommended_by, recommended_date as recommended_at
				  from '.$table.' r
				  WHERE r.authorised_person='.$_SESSION['PBI_ID'].' and
				  r.req_category not in ("1500010000") and 	
				  
				  status="'.$required_status.'"				  
				   order by r.'.$unique.' DESC';}
?>



<?php require_once 'header_content.php'; ?>
<script type="text/javascript">
        function DoNavPOPUP(lk)
        {myWindow = window.open("<?=$page?>?<?=$unique?>="+lk, "myWindow", "toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no,directories=0,toolbar=0,scrollbars=1,location=0,statusbar=1,menubar=0,resizable=1,width=800,height=500,left = 250,top = -1");}
    </script>
<?php require_once 'body_content.php'; ?>

 <?php if(!isset($_GET[$unique])){ ?>
     <form  name="addem" id="addem" class="form-horizontal form-label-left" method="post" >
         <table align="center" style="width: 50%;">
             <tr><td>
                     <input type="date" style="width:150px; font-size: 11px; height: 25px"  value="<?php if(isset($_POST[f_date])) echo $_POST[f_date]; else echo date('Y-m-01');?>" max="<?=date('Y-m-d');?>" required   name="f_date" ></td>
                 <td style="width:10px; text-align:center"> -</td>
                 <td><input type="date" style="width:150px;font-size: 11px; height: 25px"  value="<?php if(isset($_POST[t_date])) { echo $_POST[t_date]; } else { echo date('Y-m-d'); }?>" max="<?=date('Y-m-d')?>" required   name="t_date"></td>
                 <td style="padding:10px"><button type="submit" style="font-size: 11px; height: 30px" name="viewreport"  class="btn btn-primary">View authorised requisition</button></td>
             </tr></table>
         <?=$crud->report_templates_with_data($res,$link)?>
     </form>
 <?php } ?>

<?php if(isset($_GET[$unique])){ ?>
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="x_panel">
                            <div class="x_content">
                                <form  name="addem" id="addem" class="form-horizontal form-label-left" method="post">
                                    <? require_once 'support_html.php';?>
                                   <table class="table table-striped table-bordered" style="width:100%;font-size:11px">
                   <thead>
                    <tr style="background-color: bisque">
                     <th style="width: 2%">#</th>
                     <th style="">Req. No</th>
                     <!--th style="">Req. Date</th-->
                     <th style="">Item Description</th>
                     <th style="">Unit</th>
                     <th style="">Request Qty</th>
                     <th style="">Rec. Qty</th>
                     <th style="">Auth. Qty</th>
                     <th style="">Already Taken<br /> (Current Year)</th>  
                     <th>Deleted ?</th>                                        
                     </tr>
                     </thead>
                      <tbody>
                      <?php 
if($_GET[deleteid]){
	
	mysql_query("Delete From ".$table_details." where ".$unique."=".$$unique." and id='$_GET[id]'"); ?>
<meta http-equiv="refresh" content="0;<?=$page;?>?<?=$unique;?>=<?php echo $_GET[$unique]; ?>">	
<?php } ?>
                 <? 	$res=mysql_query('Select td.*,i.* from '.$table_details.' td,
				 item_info i
				  where td.item_id=i.item_id and 				  
				  td.'.$unique.'='.$_GET[$unique].'');
				   while($req_data=mysql_fetch_object($res)){
					   
					   
					   
					   $qty=$_POST['qty_'.$req_data->id];
					   if(isset($_POST[authorised])){
					   
mysql_query("Update ".$table_details." SET qty=".$qty." where ".$unique."=".$_GET[$unique]." and id=".$req_data->id."");

					   }
				   ?>
                   <tr>
                                <td><?=$i=$i+1;?></td>
                                <td><?=$req_data->$unique;?></td>
                                <!--td><?=$req_data->oi_date;?></td-->
                                <td><?=$req_data->item_name;?></td>
                                <td><?=$req_data->unit_name;?></td>
                                <td style="text-align:center"><?=$req_data->qty;?></td>
                                <td style="text-align:center"><?=$req_data->recommend_qty;?></td>
                                <td><input type="text" name="qty<?=$req_data->id;?>" id="qty<?=$req_data->id;?>" value="<?=$req_data->recommend_qty;?>" style="width:80px" /></td>
                                <td style="text-align:center"><?=$taken=getSVALUE("".$table_details."", "SUM(qty)", " where oi_date between '$dfrom' and '$dto' and  oi_no not in ('".$_GET[$unique]."') and issued_to=".$_SESSION[PBI_ID]." and item_id=".$req_data->item_id."");?> <?=$req_data->unit_name;?>'s</td>
                                <td style="text-align:center">
                                <?php if($current_status!=$required_status){ echo 'Done';} else { ?>
                                <a onclick='return window.confirm("Mr. <?php echo $_SESSION['userfname']; ?>, Are you sure you want to Delete the Item?");' href="<?=$page?>?<?=$unique?>=<?php echo $_GET[$unique]; ?>&id=<?=$req_data->id;?>&deleteid=confrim" style="text-align:center"><img src="delete.png" style="margin-left:10px" height="20" width="20" /></a>
                                <?php } ?>
                                </td>
                                
                                </tr>
                                <?php } ?>
                                
                                </tbody>
                                </table>
                                
                                <?php
                                if(isset($_POST[authorised])){
								mysql_query("Update ".$table." SET status='".$authorused_status."',authorised_date='$todayss' where ".$unique."=".$_GET[$unique]."");
					   
					   /// fint authorised person name
$chid=find_a_field('warehouse_other_issue','authorised_person',''.$unique.'='.$_GET[$unique]);
$maild=find_a_field('essential_info','ESS_CORPORATE_EMAIL','PBI_ID='.$chid);

$cby=find_a_field('warehouse_other_issue','issued_to','oi_no='.$_GET[$unique]);

///////////////////////// to authorise	
				
                $hrexecutive='shanto@icpbd.com';
	$hrmanager='g.majid@icpbd.com';
	
	 
		///////////////////////// to admin	
				$to = $hrexecutive;
				$subject = "Approved Requisition for ".$catgname;
				$txt1 = "<p>Dear Admin,</p>
				
				<p>An approved requisition is waiting for your action. Please check and take necessary actions to solve.</p>
				
				<p>Requisition By- ".$name."</p>
				<p>Recommended By- ".$name2."</p>
				<p>Authorised By- ".$name3."</p>
				
				<p><b><em>This EMAIL is automatically generated by ERP Software</em>.</b></p>";
				
				$txt=$txt1.$txt2.$tr;
				$from = 'erp@icpbd.com';
				$headers = "";
$headers .= "From: ERP Software<erp@".$_SERVER['SERVER_NAME']."> \r\n";
$headers .= "Reply-To:" . $from . "\r\n" ."X-Mailer: PHP/" . phpversion();
$headers .= 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Cc: g.majid@icpbd.com' . "\n";
$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";        
mail($to,$subject,$txt,$headers);
				
				
				
				
				
				
				
				
				
	///////////////////////// reply			
				$to = $creadtby;
				$subject = "Approved Your Requisition";
				$txt1 = "<p>Dear ".$name. "</p>
				
				<p>Your Requisition is Approved. Please contact with admin.</p>
				
				
				<p>Recommended By- ".$name2."</p>
				<p>Authorised By- ".$name3."</p>
				
				<p><b><em>This EMAIL is automatically generated by ERP Software.</em></b></p>";
				
				$txt=$txt1.$txt2.$tr;
				$from = 'erp@icpbd.com';
				$headers = "";
$headers .= "From: ERP Software<erp@".$_SERVER['SERVER_NAME']."> \r\n";
$headers .= "Reply-To:" . $from . "\r\n" ."X-Mailer: PHP/" . phpversion();
$headers .= 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";        
mail($to,$subject,$txt,$headers); 
					   
					   
					   echo "<script>self.opener.location = '$page'; self.blur(); </script>";
                       echo "<script>window.close(); </script>";
								}
								?>
                                    
                                     <?php if($current_status!=$required_status){ echo '<h5 style="text-align:center; color:red; font-weight:bold"><i>This requisition has been Authorised!!</i></h5>';} else { ?>
                                     <table style="width:100%;font-size:12px">
                                     <tr><td>
                                           <input type="text" id="return_comments"  name="return_comments" class="form-control col-md-7 col-xs-12"  style="width:166px; font-size: 11px" placeholder="return comments........" >
                                           </td><td></td></tr>
                                          <tr>
                                          <td>
                                           <button type="submit" name="Return" id="Return" style="font-size:12px" class="btn btn-danger" onclick='return window.confirm("Are you confirm to Return?");'>Return the Requisition</button>
                                           </td>
                                             
                                             <!--td>
                                             <div class="form-group">
                                             <div class="col-md-6 col-sm-6 col-xs-12">
                                           <button type="submit" onclick='return window.confirm("Are you confirm to Deleted?");' name="Deleted" id="Deleted" style="font-size:12px" class="btn btn-danger">Cancel & Deleted</button>
                                             </div></div></td-->
                                             
                                                                                       
                                            
                                            <td>
                                           <button type="submit" onclick='return window.confirm("Are you confirm to Recommended the Requisition?");' style="font-size:12px" name="authorised" id="authorised" class="btn btn-primary">Authorize & Forward to HR</button>
                                           </td></tr></table>
                                            <?php } ?>                               
                                                                                                                                   
                                    


                                </form>
                                </div>
                                </div>
                                </div>
<?php } ?>


                
        
<?php require_once 'footer_content.php' ?>