 <?php
require_once 'support_file.php';
$title="Apply for Outdoor Duty";

$now=time();
$unique='id';
$unique_field='attendance_date';
$table="hrm_od_attendance";
$page="hrm_apply_for_outdoor_duty.php";
$crud      =new crud($table);
$$unique = $_GET[$unique];
$targeturl="<meta http-equiv='refresh' content='0;$page'>";

if(prevent_multi_submit()){
if(isset($_POST[$unique_field]))

//for insert..................................
{    $$unique = $_POST[$unique];
    if(isset($_POST['record']))
    {		
		$sd=$_POST[attendance_date]; 
		$_POST[attendance_date]=date('Y-m-d' , strtotime($sd));	
		$_POST[PBI_ID]=$_SESSION[PBI_ID];
		$_POST[entry_by]=$_SESSION[PBI_ID];
		$_POST[status] = "PENDING";
        $_POST[entry_at] = date('Y-m-d H:i:s');
        $at=$_POST['late_entry_at'];
        $_POST['late_entry_at']=$at.',  '.$_POST[am_pm];
        $crud->insert();
        $type=1;
        $msg='New Entry Successfully Inserted.';
		
		
$PBI_DEPT_HEADemail=$_POST[authorised_by];
$myid=$_SESSION['PBI_ID'];
$name=find_a_field('personnel_basic_info','PBI_NAME','PBI_ID='.$myid);
$emailId=find_a_field('essential_info','ESS_CORPORATE_EMAIL','PBI_ID='.$PBI_DEPT_HEADemail);
	
	 
		//if($emailId!=''){
				$to = $emailId;
				$subject = "Apply for Outdoor Duty";
				$txt1 = "<p>Dear Sir,</p>				
				<p>An Outdoor Duty Attendance Application is pending for your Authorization. Please enter employee access module to authorise the Application. </p>				
				<p>Applied By- ".$name."</p>				
				<p><b><i>This EMAIL is automatically generated by ERP Software.</i></b></p>";				
				$txt=$txt1.$txt2.$tr;				
				$from = 'erp@icpbd.com';
				$headers = "";
				$headers .= "From: ERP Software<erp@".$_SERVER['SERVER_NAME']."> \r\n";
$headers .= "Reply-To:" . $from . "\r\n" ."X-Mailer: PHP/" . phpversion();
$headers .= 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Cc:' .$email_CC. "\n";
$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";        
mail($to,$subject,$txt,$headers);
        unset($_POST);
        unset($$unique);
    }
    
    
//for modify..................................
if(isset($_POST['modify']))
{
    $_POST['edit_at']=time();
    $_POST['edit_by']=$_SESSION['userid'];
    $at=$_POST['late_entry_at'];
    $_POST['late_entry_at']=$at.',  '.$_POST[am_pm];

    $crud->update($unique);
    $type=1;
    //echo $targeturl;
    echo "<script>self.opener.location = '$page'; self.blur(); </script>";
    echo "<script>window.close(); </script>";
}

//for Delete..................................
if(isset($_POST['delete']))
{   $condition=$unique."=".$$unique;
    $crud->delete($condition);
    unset($$unique);
    $type=1;
    $msg='Successfully Deleted.';
    echo "<script>self.opener.location = '$page'; self.blur(); </script>";
    echo "<script>window.close(); </script>";
}}}

// data query..................................
if(isset($$unique))
{   $condition=$unique."=".$$unique;
    $data=db_fetch_object($table,$condition);
    while (list($key, $value)=each($data))
    { $$key=$value;}}
?>



<?php require_once 'header_content.php'; ?>
 <style>
     input[type=text]{
         font-size: 11px;
     }
 </style>
<script type="text/javascript">
        function DoNavPOPUP(lk)
        {myWindow = window.open("<?=$page?>?<?=$unique?>="+lk, "myWindow", "toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no,directories=0,toolbar=0,scrollbars=1,location=0,statusbar=1,menubar=0,resizable=1,width=600,height=600,left = 383,top = -1");}
    </script>
<?php require_once 'body_content.php'; ?>



                    <!-- input section-->
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="x_panel">
                            <div class="x_title">
                                <h2><?=$title;?></h2>
                                <ul class="nav navbar-right panel_toolbox">
                                    <div class="input-group pull-right">
                                        <!--a target="_new" class="btn btn-sm btn-default"  href="user_permission2.php">
                                            <i class="fa fa-plus-circle"></i> <span class="language" style="color:#000">Uer Permission (SUB)</span>
                                        </a-->
                                    </div>
                                </ul>
                                <div class="clearfix"></div>
                            </div>
                            <div class="x_content">

                                <form  name="addem" id="addem" class="form-horizontal form-label-left" method="post" style="font-size: 11px">
                                    <? require_once 'support_html.php';?>
                                    
                                    <table style="width:100%; font-size: 11px"  cellpadding="0" cellspacing="0">
                                    <tr>
                                    <td style="width:50%">
                                    <div class="form-group">
             <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width:25%">OD Date<span class="required">*</span></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" id="attendance_date"  required="required" name="attendance_date"  class="form-control col-md-7 col-xs-12" >
                                        <input type="hidden" id="<?=$unique?>" style="width:100%"     name="<?=$unique?>" value="<?=$$unique?>" class="form-control col-md-7 col-xs-12" >
                                        </div></div> 
                                        </td>
                                        
                                        
                                                                          
                                    <td>
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width:30%">Duty Place<span class="required">*</span></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" id="place" style="width:100%"  required   name="place"  value="<?=$place;?>"  class="form-control col-md-7 col-xs-12" >
                                    </div></div>
                                    </td>
                                    </tr>                                   
                                    
                                  
                                    
                                   
                                    
                                    <tr>
                                    <td>
                                    <div class="form-group">
          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width:25%">Purpose<span class="required">*</span></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
            <input type="text" id="late_reason" style="width:100%"  required   name="late_reason"   class="form-control col-md-7 col-xs-12" >
                                        </div></div> 
                                        </td>
                                        
                                        
                                                                          
                                    <td>
                                    <div class="form-group">
         <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width:30%">Authorised Person<span class="required">*</span></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <select class="select2_single form-control" style="width: 100%;" tabindex="-1" required="required" name="authorised_by" id="authorised_by">
                                                <option></option>
                                                <? $sql_recommended_by="SELECT  p.PBI_ID,concat(p.PBI_ID_UNIQUE,' : ',p.PBI_NAME,' : ',d.DEPT_SHORT_NAME) FROM 
							 
							personnel_basic_info p,
							department d
							 where 
							 p.PBI_JOB_STATUS in ('In Service') and 							 
							 p.PBI_DEPARTMENT=d.DEPT_ID					 
							  order by p.PBI_NAME";
                                                advance_foreign_relation($sql_recommended_by,$authorised_by);?>
                                            </select>
                                    </div></div>
                                    </td>
                                    </tr>
                                    </table>
                                    
                                  

                                        <br>
                                        <?php if($_GET[$unique]){  ?>                                            
                                            <div class="form-group" style="margin-left:40%">
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                            <button type="submit" name="modify" id="modify" class="btn btn-success" style="font-size: 12px">Modify</button>
                                            </div></div>
                                            <? if($_SESSION['userid']=="10019"){?>                                            
                                             <div class="form-group" style="margin-left:40%;">
                                             <div class="col-md-6 col-sm-6 col-xs-12">
                                             <input  name="delete" type="submit" class="btn btn-danger" style="font-size: 12px" id="delete" value="Delete"/>
                                             </div></div>                                             
                                             <? }?>                                         
                                            <?php } else {?>                                           
                                            <div class="form-group" style="margin-left:40%">
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                            <button type="submit" name="record" id="record" style="font-size: 12px" onclick='return window.confirm("Are you confirm?");' class="btn btn-primary">Apply for Outdoor Duty</button>
                                            </div></div>                                                                                        
                                            <?php } ?> 


                                </form>
                                </div>
                                </div>
                                </div>

                    <?php if(!isset($_GET[$unique])){ ?>
                    <!-------------------list view ------------------------->
                    <!--div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="x_panel">
                            <div class="x_title">
                                <h2>Late Attendance History</h2>
                                <div class="clearfix"></div>
                            </div>

                            <div class="x_content">
                            <table id="datatable-buttons" class="table table-striped table-bordered" style="width:100%;font-size:11px">
                   <thead>
                    <tr>
                     <th style="width: 2%">#</th>
                     <th style="">ID</th>
                     <th style="">Date</th>
                     <th style="">Duty Place</th>
                     <th style="">Purpose</th>
                     <th style="">Status</th>
                     <th style="">Entry At</th>
                     <th style="">Recommended By</th>
                     <th style="">Recommended At</th>                                          
                     </tr>
                     </thead>
                      <tbody>
                                <? 	$res=mysqli_query($conn,"select l.id, a.PBI_NAME, l.attendance_date, l.place, l.late_reason,status,entry_at,authorised_at as Recommended_at, (select PBI_NAME from personnel_basic_info where PBI_ID=a.PBI_ID) as Recommended_by from personnel_basic_info a, ".$table." l where  a.PBI_ID=l.PBI_ID and  l.PBI_ID='".$_SESSION[PBI_ID]."'     order by l.attendance_date desc");
								 while($leavedata=mysqli_fetch_object($res)){
                                ?>
                                <tr style="cursor: pointer" onclick="DoNavPOPUP('<?=$data->po_no?>', 'TEST!?', 900, 600)">
                                <td><?=$i=$i+1;?></td>
                                <td><?=$leavedata->id;?></td>
                                <td><?=$leavedata->attendance_date;?></td>
                                <td><?=$leavedata->place;?></td>
                                <td><?=$leavedata->late_reason;?></td>
                                <td><?=$leavedata->status;?></td>
                                <td><?=$leavedata->entry_at;?></td>
                                <td><?=$leavedata->Recommended_by;?></td>
                                <td><?=$leavedata->Recommended_at;?></td>
                                </tr>
                                
                                <?php } ?>
                                
                                </tbody>
                                </table>
                              
                            </div>

                        </div></div-->
                    <!-------------------End of  List View --------------------->
                    <?php } ?>
                    <!---page content----->


                
        
<?php require_once 'footer_content.php' ?>
<script>
    $(document).ready(function() {
        $('#attendance_date').daterangepicker({

            singleDatePicker: true,
            calender_style: "picker_4",

        }, function(start, end, label) {
            console.log(start.toISOString(), end.toISOString(), label);
        });
    });
</script>

