<?php
require_once 'support_file.php';
$title='Work Order';

$table_master='purchase_master';
$table_details='purchase_invoice';
$unique='po_no';



if(isset($_REQUEST['unsetPoNo']) && $_REQUEST['unsetPoNo']>0){
    unset($_SESSION[$unique]);
    echo '<script type="text/javascript">parent.parent.document.location.href = "po_create_item.php";</script>';
}



if(isset($_POST['new'])){

    $crud   = new crud($table_master);
    if(!isset($_SESSION[$unique])) {
        $_POST['entry_by']=$_SESSION['userid'];
        $_POST['entry_at']=date('Y-m-d h:s:i');
        $_POST['edit_by']=$_SESSION['userid'];
        $_POST['edit_at']=date('Y-m-d h:s:i');
        $crud->insert();
        $$unique=$_SESSION[$unique]=$_POST[$unique];


        if($_FILES['qoutationDoc']['tmp_name']!=''){
            $file_temp = $_FILES['qoutationDoc']['tmp_name'];
            $folder = "../../po_documents/qoutationDoc/";
            move_uploaded_file($file_temp, $folder.$$unique.".pdf");}

        if($_FILES['mailCommDoc']['tmp_name']!=''){
            $file_temp = $_FILES['mailCommDoc']['tmp_name'];
            $folder = "../../po_documents/mailCommDoc/";
            move_uploaded_file($file_temp, $folder.$$unique.".pdf");}

        unset($$unique);
        $type=1;
        $msg='Work Order No Created. (PO No :-'.$_SESSION[$unique].')';

    }

    else {

        $_POST['edit_by']=$_SESSION['userid'];
        $_POST['edit_at']=date('Y-m-d h:s:i');
        $crud->update($unique);
        if($_FILES['qoutationDoc']['tmp_name']!=''){
            $file_temp = $_FILES['qoutationDoc']['tmp_name'];
            $folder = "../../po_documents/qoutationDoc/";
            move_uploaded_file($file_temp, $folder.$$unique.".pdf");}

        if($_FILES['mailCommDoc']['tmp_name']!=''){
            $file_temp = $_FILES['mailCommDoc']['tmp_name'];
            $folder = "../../po_documents/mailCommDoc/";
            move_uploaded_file($file_temp, $folder.$$unique.".pdf");}
        $type=1;
        $msg='Successfully Updated.';
    }}





$$unique=$_SESSION[$unique]=$_POST[$unique];

if(isset($_POST['delete']))

{		$crud   = new crud($table_master);
    $condition=$unique."=".$$unique;
    $crud->delete($condition);
    $crud   = new crud($table_details);
    $condition=$unique."=".$$unique;
    $crud->delete_all($condition);
    unset($$unique);
    unset($_SESSION[$unique]);
    $type=1;
    $msg='Successfully Deleted.';}


if($_GET['del']>0)

{		$crud   = new crud($table_details);
    $condition="id=".$_GET['del'];
    $crud->delete_all($condition);
    $type=1;
    $msg='Successfully Deleted.';
}





if(isset($_POST['confirmm']))

{
    unset($_POST);
    $_POST[$unique]=$$unique;
    $_POST['entry_by']=$_SESSION['userid'];
    $_POST['entry_at']=date('Y-m-d h:s:i');
    $_POST['status']='UNCHECKED';
    $crud   = new crud($table_master);
    $crud->update($unique);

    $chid=find_a_field('purchase_master','checkby','po_no='.$$unique);
    $maild=find_a_field('essential_info','ESS_CORPORATE_EMAIL','PBI_ID='.$chid);

    if($maild!=''){
        $to = $maild;
        $subject = "New Work order";
        $txt = "<p>Dear Sir,</p>
				<p>A new work order has been created. WO No is: <b>".$$unique."</b></p>
				<p>Need your approval. <b>Please enter Employee Access module to check the work order<b></p>
				
				<p>Prepared By- <b>".find_a_field('user_activity_management','fname','user_id='.$_SESSION['user']['id'])."<b></p>
				<p>This EMAIL is automatically generated by ERP Software.</p>";

        $from = 'erp@icpbd.com';
        $headers = "";
        $headers .= "From: ICP ERP <erp@icpbd.com> \r\n";
        $headers .= "Reply-To:" . $from . "\r\n" ."X-Mailer: PHP/" . phpversion();
        $headers .= 'MIME-Version: 1.0' . "\r\n";
        $headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
        mail($to,$subject,$txt,$headers);
    }

    unset($$unique);
    unset($_SESSION[$unique]);
    $type=1;
    $msg='Successfully Forwarded for Approval.';
}



if(isset($_POST['add'])&&($_POST[$unique]>0))
{		$crud   = new crud($table_details);
    $iii=explode('#>',$_POST['item_id']);
    $_POST['item_id']=$iii[1];
    $_POST['entry_by']=$_SESSION['userid'];
    $_POST['entry_at']=date('Y-m-d h:s:i');
    $_POST['edit_by']=$_SESSION['userid'];
    $_POST['edit_at']=date('Y-m-d h:s:i');
    $crud->insert();}



if($$unique>0)

{		$condition=$unique."=".$$unique;
    $data=db_fetch_object($table_master,$condition);
    while (list($key, $value)=each($data))
    { $$key=$value;}}


if($$unique>0) $btn_name='Update PO Information'; else $btn_name='Initiate PO Information';

if($_SESSION[$unique]<1)
    $$unique=db_last_insert_id($table_master,$unique);
?>

<?php require_once 'header_content.php'; ?>
<?php require_once 'body_content.php'; ?>

              

              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo $title; ?></h2>
                     <ul class="nav navbar-right panel_toolbox">
                     <div class="input-group pull-right">
								<!--a target="_new" class="btn btn-sm btn-default"  href="production_manual_and_return.php">
									<i class="fa fa-plus-circle"></i> <span class="language" style="color:#000">MANUAL & Return Production</span>
								</a-->

                               </div>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <br />
                              
                    

<?php 
$initiate=$_POST[initiate];

$d =$_POST[ps_date];
$ps_date=date('Y-m-d' , strtotime($d)); 
$invoice=$_POST[invoice];
$billno=$_POST[billno];
$enat=date('Y-m-d h:s:i');
if(isset($initiate)){	
	
$insert=mysql_query("INSERT INTO production_floor_receive_master (custom_pr_no,pr_date,warehouse_from,warehouse_to,ip,entry_by,entry_at,status,remarks)  VALUES ('$invoice','$ps_date','$_POST[warehouse_id]','$_POST[warehouse_id]','$ip','$_SESSION[userid]','$enat','MANUAL','$_POST[remarkspro]')");	

$_SESSION[initiate_daily_production]=$invoice;
$_SESSION[pr_no] =getSVALUE("production_floor_receive_master", "pr_no", " where custom_pr_no='$_SESSION[initiate_daily_production]'");
;

}


if(isset($_POST[updatePS])){	
	
mysql_query("UPDATE production_floor_receive_master SET  pr_date='$ps_date',warehouse_to='$_POST[warehouse_id]' WHERE custom_pr_no='".$_SESSION[initiate_daily_production]."' ");	


}



$resultsssss=mysql_query("Select * from production_floor_receive_master where custom_pr_no='$_SESSION[initiate_daily_production]' and custom_pr_no!='0'");
$inirow=mysql_fetch_array($resultsssss);

 
 
 $ofp=getSVALUE("production_floor_receive_detail", "Sum(no_of_pack)", " where custom_pr_no='$_SESSION[initiate_daily_production]'");
 $ratesss=getSVALUE("production_floor_receive_detail", "Sum(rate) as rate", " where custom_pr_no='$_SESSION[initiate_daily_production]'");
 $amountsss=getSVALUE("production_floor_receive_detail", "Sum(amount) as amount", " where custom_pr_no='$_SESSION[initiate_daily_production]'");
 ?>   



                    
 <form  name="addem" id="addem" class="form-horizontal form-label-left" method="post">
     <?require_once 'support_html.php';?>
     <table style="width:100%; font-size: 12px">
         <tr>

             <td>
                 <div class="form-group">
                     <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">PO No<span class="required">*</span></label>
                     <div class="col-md-6 col-sm-6 col-xs-12">
                         <input type="text" id="po_no" style="width:100%" name="po_no" value="<?=$po_no;?>" class="form-control col-md-7 col-xs-12" >
                     </div></div></td>


             <td>
                 <div class="form-group">
                     <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">PO Date<span class="required">*</span></label>
                     <div class="col-md-6 col-sm-6 col-xs-12">
                         <input type="text" id="po_date" style="width:100%" name="po_date" value="<?=$po_date;?>" class="form-control col-md-7 col-xs-12" >
                     </div></div></td>


             <td>
                 <div class="form-group">
                     <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">Final Destination<span class="required">*</span></label>
                     <div class="col-md-6 col-sm-6 col-xs-12">
                         <select class="select2_single form-control" name="warehouse_id" id="warehouse_id">
                             <? foreign_relation('warehouse','warehouse_id','warehouse_name',$warehouse_id);
                             ?>
                         </select></div></div></td></tr>


         <tr>

             <td><div class="form-group">
                     <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">Vendor<span class="required">*</span></label>
                     <div class="col-md-6 col-sm-6 col-xs-12">
                         <select class="select2_single form-control" name="vendor_id" id="vendor_id">
                             <? foreign_relation('vendor','vendor_id','vendor_name',$vendor_id);
                             ?>
                         </select>

                         <? if($vendor_id>0){
                             $vendor = find_all_field('vendor','','vendor_id='.$vendor_id);
                         } ?>

                     </div></div></td>

             <td></td>
             <td></td>
         </tr>


         <tr><td>
                 <div class="form-group">
                     <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">Req No<span class="required">*</span></label>
                     <div class="col-md-6 col-sm-6 col-xs-12">
                         <input type="text" id="req_no" style="width:100%" name="req_no" value="<?=$req_no;?>" class="form-control col-md-7 col-xs-12" >
                     </div></div>
             </td>




             <td>
                 <div class="form-group">
                     <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">Transport Bill<span class="required">*</span></label>
                     <div class="col-md-6 col-sm-6 col-xs-12">
                         <input type="text" id="transport_bill" style="width:100%" name="transport_bill" value="<?=$transport_bill;?>" class="form-control col-md-7 col-xs-12" >
                     </div></div></td>



             <td>
                 <div class="form-group">
                     <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">Labor bill<span class="required">*</span></label>
                     <div class="col-md-6 col-sm-6 col-xs-12">
                         <input type="text" id="labor_bill" style="width:100%" name="labor_bill" value="<?=$labor_bill;?>" class="form-control col-md-7 col-xs-12" >
                     </div></div></td></tr>

         <tr>
             <td>
                 <div class="form-group">
                     <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">VAT<span class="required">*</span></label>
                     <div class="col-md-6 col-sm-6 col-xs-12">
                         <input type="text" id="tax" style="width:100%" name="tax" value="<?=$tax;?>" class="form-control col-md-7 col-xs-12" >
                     </div></div>
             </td>


             <td>
                 <div class="form-group">
                     <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">Tax<span class="required">*</span></label>
                     <div class="col-md-6 col-sm-6 col-xs-12">
                         <input type="text" id="tax_ait" style="width:100%" name="tax_ait" value="<?=$tax_ait;?>" class="form-control col-md-7 col-xs-12" >
                     </div></div>
             </td>


             <td>
                 <div class="form-group">
                     <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">Service Charge<span class="required">*</span></label>
                     <div class="col-md-6 col-sm-6 col-xs-12">
                         <input type="text" id="asf" style="width:100%" name="asf" value="<?=$asf;?>" class="form-control col-md-7 col-xs-12" >
                     </div></div>
             </td></tr>


         <tr>
             <td><div class="form-group">
                     <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">Quotation No<span class="required">*</span></label>
                     <div class="col-md-6 col-sm-6 col-xs-12">
                         <input type="text" id="quotation_no" style="width:100%" name="quotation_no" value="<?=$quotation_no;?>" class="form-control col-md-7 col-xs-12" >
                     </div></div></td>

             <td><div class="form-group">
                     <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">Quotation Date<span class="required">*</span></label>
                     <div class="col-md-6 col-sm-6 col-xs-12">
                         <input type="text" id="quotation_date" style="width:100%" name="quotation_date" value="<?=$quotation_date;?>" class="form-control col-md-7 col-xs-12" >
                     </div></div></td>

             <td><div class="form-group">
                     <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">Delivery Within<span class="required">*</span></label>
                     <div class="col-md-6 col-sm-6 col-xs-12">
                         <input type="text" id="delivery_within" style="width:100%" name="delivery_within" value="<?=$delivery_within;?>" class="form-control col-md-7 col-xs-12" >
                     </div></div></td>
         </tr>



         <tr> <td><div class="form-group">
                     <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">Payment Terms<span class="required">*</span></label>
                     <div class="col-md-6 col-sm-6 col-xs-12">
                         <input type="text" id="payment_terms" style="width:100%" name="payment_terms" value="<?=$payment_terms;?>" class="form-control col-md-7 col-xs-12" >
                     </div></div></td>

             <td><div class="form-group">
                     <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">Currency<span class="required">*</span></label>
                     <div class="col-md-6 col-sm-6 col-xs-12">
                         <select class="select2_single form-control" name="currency">

                             <option value="BDT"  <?php echo ($currency =='BDT')?'selected':''?>>BDT ৳</option>
                             <option value="USD" <?php echo ($currency =='USD')?'selected':''?>>USD $</option>
                             <option value="0">-- Select Currency --</option>
                         </select>
                     </div></div></td>

             <td><div class="form-group">
                     <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">Delivery Within<span class="required">*</span></label>
                     <div class="col-md-6 col-sm-6 col-xs-12">
                         <input type="text" id="delivery_within" style="width:100%" name="delivery_within" value="<?=$delivery_within;?>" class="form-control col-md-7 col-xs-12" >
                     </div></div></td> </tr>



         <tr>
             <td>
                 <div class="form-group">
                     <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">PO Details<span class="required">*</span></label>
                     <div class="col-md-6 col-sm-6 col-xs-12">
                         <textarea  id="po_details" style="width:100%" name="po_details"  class="form-control col-md-7 col-xs-12" ><?=$po_details;?></textarea>
                     </div></div></td>


             <td>

                 <div class="form-group">
                     <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">Qoutation (*PDF)<span class="required">*</span></label>
                     <div class="col-md-6 col-sm-6 col-xs-12">
                         <input type="text" id="qoutationDoc" style="width:100%" name="qoutationDoc" value="<?=$qoutationDoc;?>" class="form-control col-md-7 col-xs-12" >
                     </div></div>
             </td>


             <td>
                 <div class="form-group">
                     <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">Mail (*PDF)<span class="required">*</span></label>
                     <div class="col-md-6 col-sm-6 col-xs-12">
                         <input type="text" id="mailCommDoc" style="width:100%" name="mailCommDoc" value="<?=$mailCommDoc;?>" class="form-control col-md-7 col-xs-12" >
                     </div></div>
             </td> </tr>




         <tr>

             <td><div class="form-group">
                     <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">Checked By<span class="required">*</span></label>
                     <div class="col-md-6 col-sm-6 col-xs-12">
                         <input type="text" id="checkby" style="width:100%" name="checkby" value="<?=$checkby;?>" class="form-control col-md-7 col-xs-12" >
                     </div></div></td>

             <td><div class="form-group">
                     <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">Recommended By<span class="required">*</span></label>
                     <div class="col-md-6 col-sm-6 col-xs-12">
                         <input type="text" id="recommended" style="width:100%" name="recommended" value="<?=$recommended;?>" class="form-control col-md-7 col-xs-12" >
                     </div></div></td>

             <td><div class="form-group">
                     <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name" style="width: 40%">Authorised By<span class="required">*</span></label>
                     <div class="col-md-6 col-sm-6 col-xs-12">
                         <input type="text" id="authorise" style="width:100%" name="authorise" value="<?=$authorise;?>" class="form-control col-md-7 col-xs-12" >
                     </div></div></td>
         </tr>



       <tr>
       <td colspan="4">
           <div class="form-group" style="margin-left:40%">
               <div class="col-md-6 col-sm-6 col-xs-12">
               <button type="submit" name="new" onclick='return window.confirm("Are you confirm?");' class="btn btn-success"><?=$btn_name?></button>
               </div></div>   
       </td></tr></table>
                </form>
                  </div></div></div>





    <!-- input section-->
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_content">
                <br />

                <form  name="addem" id="addem" class="form-horizontal form-label-left" method="post">
                    <?require_once 'support_html.php';?>

                    <table style="width:100%" >



                        <tbody>
                        <tr>

                            <td style="width:20%" align="center">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Name<span class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select class="select2_single form-control" style="width:400px" tabindex="-1" required="required"  name="item_id" >
                                <option></option>

                                <?php
                                //$result=mysql_query("SELECT * FROM item_info where sub_group_id in ('200010000','300010000','500010000','800010000') order by item_name");

                                $result=mysql_query("SELECT f.*,i.* FROM 
							production_line_fg f,
							item_info i
							 where 
							 i.item_id=f.fg_item_id and 
							 i.sub_group_id in ('200010000','300010000','500010000','800010000') and
							 f.line_id='$inirow[warehouse_to]'
							 
							  order by i.item_name");
                                while($row=mysql_fetch_array($result)){  ?>
                                    <option  value="<?php echo $row[item_id]; ?>"><?php echo $row[finish_goods_code]; ?>-<?php echo $row[item_name]; ?> (<?=$packsizeitem=getSVALUE("item_sub_group", "sub_group_name", " where sub_group_id='$row[sub_group_id]'");?>)</option>
                                <?php } ?>
                            </select></div></div>

                            </td></tr></tbody></table>

                </form>
            </div>
        </div>
    </div>





<?php require_once 'footer_content.php' ?>