<?php require_once 'support_file.php';?>
<?=(check_permission(basename($_SERVER['SCRIPT_NAME']))>0)? '' : header('Location: dashboard.php');
$title="Asset Purchase";
$dfrom=date('Y-1-1');
$dto=date('Y-m-d');
$now=time();
$table="purchase_master";
$unique = 'po_no';   // Primary Key of this Database table
$table_details = 'purchase_invoice';
$details_unique = 'id';
$table_journal_item='journal_item';
$page="procurement_asset_purchase.php";
$crud      =new crud($table);


if(prevent_multi_submit()) {

    if (isset($_POST['initiate'])) {
        $_POST['section_id'] = $_SESSION['sectionid'];
        $_POST['company_id'] = $_SESSION['companyid'];
        $_POST['entry_by'] = $_SESSION['PBI_ID'];
        $_POST['entry_at'] = date('Y-m-d H:s:i');
        $_POST['issue_type'] = 'Asset Purchase';
        $_POST['po_type'] = 'Asset';
        $_POST['status'] = 'MANUAL';
        $_POST['entry_by'] = $_SESSION[userid];
        $_SESSION['initiate_procurement_asset_purchase'] = $_POST[$unique];
        $crud->insert();
        $type = 1;
        $msg = 'New Entry Successfully Inserted.';
        unset($_POST);
        unset($$unique);
    }


    if (isset($_POST['add'])) {
        $_POST['entry_by'] = $_SESSION['userid'];
        $_POST['entry_at'] = date('Y-m-d H:s:i');
        $_POST[or_date] = $_POST[or_date];
        $_POST['receive_type'] = 'Asset Purchase';
        $_POST['status'] = 'MANUAL';
        $_POST['recommend_qty'] = $_POST['qty'];
		$_POST['asset_id'] = find_a_field('asset_register','asset_id','item_id='.$_POST[item_id].'');
		$_POST['item_details'] = find_a_field('asset_register','item_details','item_id='.$_POST[item_id].'');
        $_POST['request_qty'] = $_POST['qty'];
        $_POST['issued_to'] = $_SESSION[PBI_ID];
		$_POST['amount'] = $_POST['qty']*$_POST['rate'];
        $_POST[oi_no] = $_SESSION['initiate_procurement_asset_purchase'];
        $crud = new crud($table_details);
        $crud->insert();
        $type = 1;
        $msg = 'New Entry Successfully Inserted.';
        unset($_POST);
        unset($$unique);
    }


//for modify..................................
    if (isset($_POST['modify'])) {
        $_POST['edit_at'] = time();
        $_POST['edit_by'] = $_SESSION['userid'];
        $crud->update($unique);
        $type = 1;

    }


}// prevent multi submit




//for Delete..................................
if(isset($_POST['deleted']))
{
    $crud = new crud($table_details);
    $condition =$unique."=".$_SESSION['initiate_procurement_asset_purchase'];
    $crud->delete_all($condition);
    $crud = new crud($table);
    $condition=$unique."=".$_SESSION['initiate_procurement_asset_purchase'];
    $crud->delete($condition);
    unset($_SESSION['initiate_procurement_asset_purchase']);
}


if(isset($_POST['confirmsave']))
{
	$results=mysqli_query($conn,"Select srd.*,i.*,ar.asset_code from ".$table_details." srd, item_info i,asset_register ar  where
 srd.item_id=i.item_id and 
 srd.asset_id=ar.asset_id and 
 srd.".$unique."='".$_SESSION[initiate_procurement_asset_purchase]."' order by srd.id");
                        while($row=mysqli_fetch_array($results)){
		$up_master=mysqli_query($conn, "UPDATE asset_register SET status='USED' where asset_id=".$row[asset_id]."");						
							}
							
    $up_master="UPDATE ".$table." SET status='UNCHECKED' where ".$unique."='$_SESSION[initiate_procurement_asset_purchase]'";
    $update_table_master=mysqli_query($conn, $up_master);
    $up_details="UPDATE ".$table_details." SET status='UNCHECKED' where ".$unique."='$_SESSION[initiate_procurement_asset_purchase]'";
    $update_table_details=mysqli_query($conn, $up_details);	
    $maild = find_a_field('essential_info', 'ESS_CORPORATE_EMAIL', 'PBI_ID=' . $_POST[checked_by]);
    if ($maild != '') {
            $to = $maild;
            $subject = "An asset has been purchased";
            $txt = "<p>Dear Sir,</p>
				<p>A new asset has been purchased. Purchased ID No is: <b>" . $_SESSION[initiate_procurement_asset_purchase] . "</b></p>
				<p>Need your approval. <b>Please enter Employee Access module to check the work order</b></p>				
				<p>Prepared By- <b>" . find_a_field('users', 'fname', 'user_id=' . $_SESSION['userid']) . "<b></p>
				<p>This EMAIL is automatically generated by ERP Software.</p>";
            $from = 'erp@icpbd.com';
            $headers = "";
            $headers .= "From: ICP ERP <erp@icpbd.com> \r\n";
            $headers .= "Reply-To:" . $from . "\r\n" . "X-Mailer: PHP/" . phpversion();
            $headers .= 'MIME-Version: 1.0' . "\r\n";
            $headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
            mail($to, $subject, $txt, $headers);
        }
	
	
	
	
    unset($_SESSION['initiate_procurement_asset_purchase']);
    unset($_POST);
} // if insert posting

//for single FG Delete..................................
$results = "Select srd.*,i.* from " . $table_details . " srd, item_info i  where
 srd.item_id=i.item_id and 
 srd." . $unique . "='$_SESSION[initiate_procurement_asset_purchase]' order by srd.id";
$query = mysqli_query($conn, $results);
while ($row = mysqli_fetch_array($query)) {
    $ids = $row[id];
    if (isset($_POST['deletedata' . $ids])) {
        $del = "DELETE FROM " . $table_details . " WHERE id='$ids' and " . $unique . "=" . $_SESSION['initiate_procurement_asset_purchase'] . "";
        $del_item = mysqli_query($conn, $del);
        unset($_POST);
    }
} // end of single item deleted..

$COUNT_details_data=find_a_field(''.$table_details.'','Count(id)',''.$unique.'='.$_SESSION['initiate_procurement_asset_purchase'].'');


// data query..................................
if(isset($_SESSION[initiate_procurement_asset_purchase]))
{   $condition=$unique."=".$_SESSION[initiate_procurement_asset_purchase];
    $data=db_fetch_object($table,$condition);
    while (list($key, $value)=each($data))
    { $$key=$value;}

    $results="Select srd.*,i.*,ar.asset_code from ".$table_details." srd, item_info i,asset_register ar  where
 srd.item_id=i.item_id and 
 srd.asset_id=ar.asset_id and 
 srd.".$unique."='".$_SESSION[initiate_procurement_asset_purchase]."' order by srd.id";
    $query=mysqli_query($conn, $results);
}

$sql_item_id="SELECT i.item_id,concat(i.item_id,' : ',i.item_name,' (',sg.sub_group_name,')') FROM  item_info i,
							item_sub_group sg,
							item_group g WHERE  
							i.sub_group_id=sg.sub_group_id and 
							 sg.group_id=g.group_id  and 
							 g.group_id not in ('500000000')					 
							  order by i.item_name";
							  
$sql_checked_by="SELECT  p.PBI_ID,concat(p.PBI_ID_UNIQUE,' : ',p.PBI_NAME,' : ',d.DEPT_SHORT_NAME) FROM 							 
							personnel_basic_info p,
							department d
							 where 
							 p.PBI_JOB_STATUS in ('In Service') and 							 
							 p.PBI_DEPARTMENT=d.DEPT_ID					 
							  order by p.PBI_NAME";
$sql_recommended_by="SELECT  p.PBI_ID,concat(p.PBI_ID_UNIQUE,' : ',p.PBI_NAME,' : ',d.DEPT_SHORT_NAME) FROM 
							 
							personnel_basic_info p,
							department d
							 where 
							 p.PBI_JOB_STATUS in ('In Service') and 							 
							 p.PBI_DEPARTMENT=d.DEPT_ID					 
							  order by p.PBI_NAME";		
 $sql_authorise_by="SELECT  p.PBI_ID,concat(p.PBI_ID_UNIQUE,' : ',p.PBI_NAME,' : ',d.DEPT_SHORT_NAME) FROM 
							 
							personnel_basic_info p,
							department d
							 where 
							 p.PBI_JOB_STATUS in ('In Service') and 							 
							 p.PBI_DEPARTMENT=d.DEPT_ID					 
							  order by p.PBI_NAME";	
?>

<?php require_once 'header_content.php'; ?>
<script>
    var x = 0;
    var y = 0;
    var z = 0;
    function calc(obj) {
        var e = obj.id.toString();
        if (e == 'qtysa') {
            x = Number(obj.value);
            y = Number(document.getElementById('rate').value);
        } else {
            x = Number(document.getElementById('qtysa').value);
            y = Number(obj.value);
        }
        z = x * y;
        document.getElementById('total').value = z;
        document.getElementById('update').innerHTML = z;
    }
</script>
<style>
    input[type=text]{
        font-size: 11px;
    }
</style>
<?php require_once 'body_content.php'; ?>




<div class="col-md-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2><?php echo $title; ?></h2>
            <ul class="nav navbar-right panel_toolbox">
                                        <a target="_new" class="btn btn-sm btn-default"  href="procurement_asset_purchased_view.php">
                                            <i class="fa fa-plus-circle"></i> <span class="language" style="color:#000">View List</span>
                                        </a>
                                </ul>
            <div class="clearfix"></div>
        </div>


        <div class="x_content">
            <form action="" enctype="multipart/form-data" style="font-size: 11px" method="post" name="addem" id="addem" >
                <? //require_once 'support_html.php';?>
                <table style="width:100%"  cellpadding="0" cellspacing="0">
                    <tr>
                    <th style="width:8%">PO NO</th>
                    <th style="width:1%; text-align:center">:</th>
                        <td style="width:20%;">                                   
                                    
                                    <input type="text" id="<?=$unique?>" style="width:20%" name="<?=$unique?>" value="<?
                                    $idGETs=find_a_field($table,'max('.$unique.')','1');
                                    if($_SESSION['initiate_procurement_asset_purchase']>0) {
                                        $idGET=$_SESSION['initiate_procurement_asset_purchase'];
                                    } else
                                    {
                                        $idGET=$idGETs+1;
                                        if($idGETs<1) $idGET = 1;
                                    }
                                    echo $idGET; ?>" readonly class="form-control col-md-7 col-xs-12" >
                    <input type="text" id="pono" style="width:60%"  name="pono" value="<?php if(!isset($pono)) echo automatic_number_generate("ICP#PO#","purchase_master","pono","create_date='".date('Y-m-d')." and pono like '$sekeyword%''"); else echo $pono;?>"  class="form-control col-md-7 col-xs-12" >
                                    </td>
                                 
                                 
                                    
                      <th style="width:12%">PO Date</th>  
                      <th style="width:1%; text-align:center">:</th>
                      <td style="width:20%">
                      <input type="date"   required="required" name="po_date" max="<?=date('Y-m-d');?>" value="<?=$po_date;?>" class="form-control col-md-7 col-xs-12" style="width:80%; font-size: 11px" >
                      </td>
                      
                      
                      
                      <th style="width:10%">Quotation No</th>  
                      <th style="width:1%; text-align:center">:</th>
                      <td style="width:20%">
                      <input type="text" name="quotation_no" id="quotation_no" value="<?=$quotation_no;?>" class="form-control col-md-7 col-xs-12" style="width: 80%;">
                      </td>
                      </tr>
<tr><td style=" height:5px"></td></tr>



                    <tr>
                    <th>Vendor</th>  
                      <th style="text-align:center">:</th>
                        <td>
                                    <select style="width: 80%;" required class="select2_single form-control" name="vendor_id" id="vendor_id">
                                        <option></option>
                                        <?php foreign_relation('vendor', 'vendor_id', 'CONCAT(vendor_id," : ", vendor_name)', $vendor_id, '1'); ?>
                                    </select></td>
                        

                    <th>Received Destination</th>  
                      <th style="text-align:center">:</th>
                        <td>
                                    <select class="select2_single form-control"  required style="width: 80%;" name="warehouse_id" id="warehouse_id"><option></option>
                                        <?php foreign_relation('warehouse', 'warehouse_id', 'CONCAT(warehouse_id," : ", warehouse_name)', $warehouse_id, 'use_type in ("WH")'); ?>
                                    </select></td>



                      <th>Remarks</th>  
                      <th style="text-align:center">:</th>
                        <td><input type="text" name="po_subject" id="po_subject" value="<?=$po_subject;?>"  class="form-control col-md-7 col-xs-12" style="width: 80%;"></td>
                    </tr> 
                    
                    
                    
                    
                    
                    
                    
            <tr><td style=" height:5px"></td></tr>  
            <tr>

                <th>Quotation Date</th>
                <th style="width:1%; text-align:center">:</th>
                <td><input type="date"  style="width:80%; font-size:11px" max="<?=date('Y-m-d');?>" name="quotation_date" value="<?=$quotation_date;?>" class="form-control col-md-7 col-xs-12" >
                </td>
                
                <th>Delivery Within</th>
                <th style="width:1%; text-align:center">:</th>
                <td><input type="date"  style="width:80%; font-size:11px" min="<?=date('Y-m-d');?>" name="delivery_within" value="<?=$delivery_within;?>" class="form-control col-md-7 col-xs-12" >
                </td>


                

                <th>Labor Bill</th>
                <th style="width:1%; text-align:center">:</th>
                <td><input type="text" id="labor_bill" name="labor_bill" style="width:80%" value="<?=$labor_bill;?>" class="form-control col-md-7 col-xs-12" >
                </td></tr>    
                    
                    
                    
              <tr><td style=" height:5px"></td></tr>
                    
              <tr>
              <th>VAT</th>
              <th style="width:1%; text-align:center">:</th>
              <td><input type="text" name="tax" id="tax" placeholder="%" value="<?=$tax;?>"  class="form-control col-md-7 col-xs-12" style="width: 80%;"></td>



              <th>TAX</th>
              <th style="width:1%; text-align:center">:</th>
              <td><input type="text" name="tax_ait" placeholder="%" id="tax_ait" value="<?=$tax_ait;?>"  class="form-control col-md-7 col-xs-12" style="width: 80%;"></td>

              <th>Transport Bill</th>
                <th style="width:1%; text-align:center">:</th>
                <td><input type="text" id="transport_bill" name="transport_bill" style="width:80%" value="<?=$transport_bill;?>" class="form-control col-md-7 col-xs-12" >
                </td>

          </tr>    
                    
                    
                    
              <tr><td style=" height:5px"></td></tr>
                    
              <tr>
              <th>Checked By</th>
              <th style="width:1%; text-align:center">:</th>
              <td>
                      <select class="select2_single form-control" style="width: 80%;" tabindex="-1" required="required" name="checkby" id="checkby">
                          <option></option>
                          <? advance_foreign_relation($sql_checked_by,$checkby);?>
                  </select>
              </td>



              <th>Recommended By</th>
              <th style="width:1%; text-align:center">:</th>
              <td>
                  <select class="select2_single form-control" style="width: 80%;" tabindex="-1" required="required" name="recommended" id="recommended">
                      <option></option>
                      <? advance_foreign_relation($sql_recommended_by,$recommended);?>
                  </select>
              </td>

              <th>Authorised By</th>
              <th style="width:1%; text-align:center">:</th>
              <td><select class="select2_single form-control" style="width: 80%;" tabindex="-1" required="required" name="authorise" id="authorise">
                      <option></option>
                      <? advance_foreign_relation($sql_authorise_by,$authorise);?>
                  </select>
                 </td>
          </tr>
                    
                    </table>











                <div class="form-group" style="margin-left:40%; margin-top: 15px">

                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <?php if($_SESSION[initiate_procurement_asset_purchase]){  ?>
                            <button type="submit" name="modify" class="btn btn-primary" onclick='return window.confirm("Are you confirm to Update?");' style="font-size: 11px">Update <?=$title;?></button>

                        <?php   } else {?>
                            <button type="submit" name="initiate" onclick='return window.confirm("Are you confirm?");' class="btn btn-primary" style="font-size: 11px">Initiate <?=$title;?></button>
                        <?php } ?>
                    </div></div>
            </form></div></div></div>











<?php if($_SESSION[initiate_procurement_asset_purchase]){  ?>

    <form action="" name="addem" id="addem" class="form-horizontal form-label-left" method="post">
        <? require_once 'support_html.php';?>
        <input type="hidden" id="vendor_id" name="vendor_id" value="<?=$vendor_id;?>" >
        <input type="hidden" id="vendor_name" name="vendor_name" value="<?=$vendor_name;?>" >
        <input type="hidden" id="warehouse_id" name="warehouse_id" value="<?=$warehouse_id;?>" >
        <input type="hidden" id="po_date" name="po_date" value="<?=$po_date;?>">
        <input type="hidden" id="<?=$unique;?>" name="<?=$unique;?>" value="<?=$_SESSION[initiate_procurement_asset_purchase];?>">
        <table align="center" style="width:98%; font-size: 11px" class="table table-striped table-bordered">
            <thead>
            <tr style="background-color: bisque">
                <th style="text-align: center">Item Description</th>
                <th style="text-align: center">Purchaes Qty</th>
                <th style="text-align: center">Unit Price</th>
                <th style="text-align: center">Unit Amount</th>
                <th style="text-align: center">Warrant Period</th>
                <th style="text-align: center"></th>
            </tr>
            </thead>

            <tbody>
            <tr>
                <td style="width:25%" align="center">
                    <select class="select2_single form-control" required name="item_id" id="item_id" style="width:100%;font-size: 11px">
                        <option></option>
                        <? $sql_item_id="SELECT i.item_id,concat(ar.asset_id,' : ',i.finish_goods_code,' : ',i.item_name,' (',sg.sub_group_name,')') FROM  item_info i,
							item_sub_group sg,
							item_group g,
							asset_register ar 
							
							WHERE  i.sub_group_id=sg.sub_group_id and 
							 sg.group_id=g.group_id and 
							 g.group_id  in ('1100000000') and 
							 i.item_id=ar.item_id and 
							 ar.status='UNUSED' order by i.item_name";
                        advance_foreign_relation($sql_item_id,$_POST[item_id]);?>
                    </select>
                </td>


                

               <td style="width:8%" align="center">
                    <input align="center" type="text" id="qty" style="width:100%; height:37px;   text-align:center"   name="qty" class="form-control col-md-7 col-xs-12"  class="qty" >
                </td>

                <td style="width:8%" align="center">
                    <input align="center" type="text" id="rate" style="width:100%; height:37px;   text-align:center"  required   name="rate"  class="form-control col-md-7 col-xs-12" class='rate' >
                </td>

                

                <td style="width:10%" align="center">
                    <input type="text" id="total_amt" style="width:100%; height:37px; font-weight:bold; text-align:center" readonly  name="total_amt" class="form-control col-md-7 col-xs-12" autocomplete="off" class='total_amt' ></td>

                <td style="width:8%" align="center">
                    <input type="date" id="warranty_period" style="width:100%; height:37px; font-size: 11px; text-align:center"  min="<?=date('Y-m-d');?>" name="mfg" class="form-control col-md-7 col-xs-12" required="required"></td>


                <td align="center" style="width:5%">
                    <button type="submit" class="btn btn-primary" name="add" id="add" style="font-size: 12px">Add</button></td></tr>
            </tbody>
        </table>
    </form>




    <!-----------------------Data Save Confirm ------------------------------------------------------------------------->


    <form id="ismail" name="ismail"  method="post" style="font-size: 11px"  class="form-horizontal form-label-left">
        <? require_once 'support_html.php';?>
        <input type="hidden" name="<?=$unique;?>" id="<?=$unique;?>" value="<?=$$unique;?>" >
        <input type="hidden" name="custom_pr_no" id="custom_pr_no" value="<?=$custom_pr_no;?>" >
        <input type="hidden" name="pr_date" id="pr_date" value="<?=$pr_date;?>">
        <input type="hidden" name="warehouse_from" id="warehouse_from" value="<?=$warehouse_from;?>">
        <input type="hidden" name="checked_by" id="checked_by" value="<?=$checked_by;?>">
        <input type="hidden" name="warehouse_to" id="warehouse_to" value="<?=$warehouse_to;?>">
        <input type="hidden" name="lot" id="lot" value="<?=$lot;?>">
        <?php if($COUNT_details_data>0) { ?>
            <table align="center" class="table table-striped table-bordered" style="width:98%">
                <thead>
                <tr style="background-color: bisque">
                    <th>SL</th>
                    <th>Code</th>
                    <th>Finish Goods</th>
                    <th style="width:5%; text-align:center">UOM</th>
                    <th style="text-align:center">Purchase Qty</th>
                    <th style="text-align:center">Unit Price</th>
                    <th style="text-align:center">Unit Amount</th>
                    <th style="text-align:center">Warrant Period</th>
                    <th style="text-align:center">#</th>
                </tr>
                </thead>
                <tbody>


                <?php

                while($row=mysqli_fetch_array($query)){
                    $i=$i+1;
                    $ids=$row[id];
                    ?>
                    <tr>
                        <td style="width:3%; vertical-align:middle"><?php echo $i; ?></td>
                        <td style="vertical-align:middle"><?=$row[asset_code];?></td>
                        <td style="vertical-align:middle; width: 25%"><?=$row[item_name];?></td>
                        <td style="vertical-align:middle; text-align:center"><?=$row[unit_name];?></td>
                        <td align="center" style=" text-align:center;vertical-align:middle;"><?=$row[qty];?></td>
                        <td align="center" style=" text-align:right;vertical-align:middle;"><?=$row[rate]; ?></td>
                        <td align="center" style="text-align:right;vertical-align:middle;"><?=number_format($row[amount],2);?></td>
                        <td align="center" style=" text-align:center;vertical-align:middle;"><?=$row[mfg]; ?></td>
                        <td align="center" style="vertical-align:middle">
                            <button type="submit" name="deletedata<?=$ids;?>" id="deletedata<?=$ids;?>" style="background-color:transparent; border:none" onclick='return window.confirm("Mr. <?php echo $_SESSION["username"]; ?>, Are you sure you want to Delete?");'><img src="delete.png" style="width:15px;  height:15px"></button>
                        </td>
                    </tr>
                    <?php  
					$ttotal_unit=$ttotal_unit+$row[qty];
                    $ttotal_amt=$ttotal_amt+$row[amount];  } ?>
                </tbody>
                <tr style="font-weight: bold">
                    <td colspan="4" style="font-weight:bold; font-size:11px" align="right">Total Purchased</td>
                    <td style="text-align:center"><?=$ttotal_unit;?></td>
                    <td align="center" ></td>
                    <td align="right" ><?=number_format($ttotal_amt,2);?></td>
                    <td align="center" ></td>
                    <td align="center" ></td>
                </tr>
            </table>
        <?php } ?>

        <button type="submit" style="float: left; margin-left: 1%; font-size: 12px" name="deleted" onclick='return window.confirm("Mr. <?php echo $_SESSION["username"]; ?>, Are you confirm to the Purchase Deleted?");' class="btn btn-danger">Delete Purchase </button>
        <?php if($COUNT_details_data>0) { ?>
            <button type="submit" style="float: right; margin-right: 1%; font-size: 12px" onclick='return window.confirm("Are you want to Finished?");' name="confirmsave" class="btn btn-success">Confirm and Finish Purchase </button>
        <?php } else { echo '';} ?>


    </form>
    <br>
<?php } ?>
<?=$html->footer_content();?>

<script>
    $(function(){
        $('#qty, #rate').keyup(function(){
            var qty = parseFloat($('#qty').val()) || 0;
            var rate = parseFloat($('#rate').val()) || 0;
            $('#total_amt').val((qty * rate).toFixed(2));
        });
    });
</script>

